### ISSUE TITLE
RSS feed is dead

### ISSUE THREAD

**Issue by beerisgood** [MicrosoftDocs/sysinternals#108]
https://blogs.technet.microsoft.com/sysinternals/rss.xml (from https://technet.microsoft.com/de-de/sysinternals) is dead.

**Comment by ashishknitcs** [comment]
See if this helps https://blogs.technet.microsoft.com/sysinternals/feed/

**Comment by beerisgood** [comment]
Thanks!
Looks good so far.

Looks like i already change it to this one and just forgot to post it here :D

**Comment by ashishknitcs** [comment]
@beerisgood  Issue may be closed now.
