### ISSUE TITLE
Bugcheck code 00000050

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/sysinternals#113]
0: kd> .bugcheck
Bugcheck code 00000050
Arguments ffffb288`402043fa 00000000`00000000 fffff80c`42651285 00000000`00000002
0: kd> kv
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr           : Args to Child                                                           : Call Site
00 fffff282`82c7b978 fffff80c`426532b8 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : PROCMON23+0x1285
01 fffff282`82c7b980 fffff80c`42653795 : ffffc90b`eeb55100 ffffc90b`fe99efb0 ffffc90b`f58b4080 ffffc90b`eeb55100 : PROCMON23+0x32b8
02 fffff282`82c7b9e0 fffff80c`42652f84 : ffffc90b`fe99ee00 ffffc90b`fe99eee0 ffffc90b`fe99eef8 00000000`000000c0 : PROCMON23+0x3795
03 fffff282`82c7ba30 fffff80c`3ecd6a8a : 00000000`c0000000 ffffc90b`fe99ee00 ffffc90b`fe99ef80 ffffc90b`00000154 : PROCMON23+0x2f84
04 fffff282`82c7ba80 fffff80c`3ecd6246 : ffffc90b`ed5a7000 fffff800`2f64cc00 00000000`00000000 00000000`00000000 : FLTMGR!FltpPerformPostCallbacks+0x47a
05 fffff282`82c7bb60 fffff80c`3ecd5ffc : fffff987`eca7aaf0 fffff800`2f972bc0 ffffc90b`feb8f960 ffffc90b`fc6d9ac0 : FLTMGR!FltpPassThroughCompletionWorker+0x76
06 fffff282`82c7bbd0 fffff800`2fdc2ce0 : ffffc90b`feb8f9c8 fffff800`2f972bc0 ffffc90b`feb8f960 ffffc90b`fc6d9ac0 : FLTMGR!FltpPassThroughCompletion+0xc
07 fffff282`82c7bc00 fffff800`2fdc2f9c : fffff800`2f972bd0 fffff800`2f972bc0 00000000`00000080 fffff800`2fdc2f70 : nt!ViPendingCompleteAfterWait+0xe8
08 fffff282`82c7bc50 fffff800`2f6d3967 : ffffc90b`ed5a7040 00000000`00000080 fffff800`2fdc2f70 00000808`00000000 : nt!ViPendingWorkerThread+0x2c
09 fffff282`82c7bc90 fffff800`2f791fb6 : fffff800`2dfae180 ffffc90b`ed5a7040 fffff800`2f6d3920 00650070`00790054 : nt!PspSystemThreadStartup+0x47
0a fffff282`82c7bce0 00000000`00000000 : fffff282`82c7c000 fffff282`82c76000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x16
0: kd> r
Last set context:
rax=ffffb288402042aa rbx=0000000000000000 rcx=ffffc90beeb55250
rdx=ffffe97c516af1aa rsi=0000000000000000 rdi=0000000000000000
rip=fffff80c42651285 rsp=fffff28282c7b978 rbp=0000000000080009
 r8=0000000000000154  r9=ffffc90beeb55100 r10=0000000000001001
r11=ffffc90beeb55100 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei ng nz na po nc
cs=0010  ss=0018  ds=0000  es=0000  fs=0000  gs=0000             efl=00010286
PROCMON23+0x1285:
fffff80c`42651285 8b040a          mov     eax,dword ptr [rdx+rcx] ds:ffffb288`402043fa=????????
0: kd> lm vm procmon23
Browse full module list
start             end                 module name
fffff80c`42650000 fffff80c`42669000   PROCMON23   (no symbols)           
    Loaded symbol image file: PROCMON23.SYS
    Image path: PROCMON23.SYS
    Image name: PROCMON23.SYS
    Browse all global symbols  functions  data
    Timestamp:        Sun Sep 10 13:52:05 2017 (59B5A5F5)
    CheckSum:         0001E54E
    ImageSize:        00019000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
    Information from resource tables:

https://correy.webs.com

**Comment by analyze-v** [comment]
Thanks kouzhudong. I contacted you offline to see if you would share the dump file with us. Please let me know
