### ISSUE TITLE
OpenBuild warning for loss of repo admin for v-kents

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/sysinternals#128]
Noticed this on a PR when the openbuild ran. This is hidden inside the OpenBuild report and doesn't bubble up to the PR text
> Owner v-kents of repository https://github.com/MicrosoftDocs/sysinternals has lost Admin permission. Please use Transfer Owner via OPS portal https://ops.microsoft.com to assign a new owner.

/cc @markrussinovich @dend

**Comment by lukekim** [comment]
Thanks for reporting this!
