### ISSUE TITLE
When using some software, SYSMON's CPU usage and IO will increase abnormally.

### ISSUE THREAD

**Issue by Nixiteam-fate** [MicrosoftDocs/sysinternals#154]
When I use an Android simulator, Sysmon's CPU usage and IO will increase abnormally.
![image](https://user-images.githubusercontent.com/7125025/53319555-bf90d500-38ca-11e9-9b4a-10f1858b8e8e.png)
![image](https://user-images.githubusercontent.com/7125025/53319579-d20b0e80-38ca-11e9-87e1-67d362062143.png)

Software download url：https://www.yeshen.com/

**Stack:**
ntoskrnl.exe!KiCpuId+0xaa
ntoskrnl.exe!KeReleaseSpinLock+0x612
ntoskrnl.exe!KeWaitForMutexObject+0x1a3
ntoskrnl.exe!KeQueryActiveProcessorCountEx+0x218
ntoskrnl.exe!RtlNumberOfSetBitsUlongPtr+0x10cd
ntoskrnl.exe!KiCpuId+0x2553
ntoskrnl.exe!RtlFindClearBits+0x2f0
ntoskrnl.exe!ExDeleteNPagedLookasideList+0x2edab
ntoskrnl.exe!ExReleaseSpinLockSharedFromDpcLevel+0xec
ntoskrnl.exe!ExAllocatePoolWithTag+0x82e
ntoskrnl.exe!ExAllocatePoolWithQuotaTag+0x55
ntoskrnl.exe!NtQueryVolumeInformationFile+0x10df
ntoskrnl.exe!NtDeviceIoControlFile+0x56
ntoskrnl.exe!longjmp+0x5b93
ntdll.dll!ZwDeviceIoControlFile+0xa
KERNELBASE.dll!SystemTimeToTzSpecificLocalTimeEx+0x1322
kernel32.dll!DeviceIoControl+0x7f
Sysmon64.exe+0xdc5b
Sysmon64.exe+0xa1871
kernel32.dll!BaseThreadInitThunk+0xd
ntdll.dll!RtlUserThreadStart+0x1d

**After closing the software:**
![image](https://user-images.githubusercontent.com/7125025/53319690-24e4c600-38cb-11e9-99f2-bebad3da26c9.png)

**Comment by Nixiteam-fate** [comment]
The problem has been found because a program used the ig75icd32.dll document.

**Comment by analyze-v** [comment]
Hello
thanks for the update. Would you like to let us know what the issue was or shall I go ahead and close it ?
MarkC (MSFT)
