### ISSUE TITLE
Link in Community is to old forum (which has expired certificate)

### ISSUE THREAD

**Issue by rjvdboon** [MicrosoftDocs/sysinternals#155]
On the sysinternals homepage in the Community page there is a link to "Sysinternals Forum" https://forum.sysinternals.com. Two problems with this:
1. The link should be to https://aka.ms/sysint-forums
2. The forum.sysinternals.com site has a certificate that expired last week (feb 19)

Also the link to the RSS feed mentioned on the community page is dead (http://forum.sysinternals.com/rss_topic_feed.asp)

**Comment by analyze-v** [comment]
The links were failing because of an expired certificate on the redirect page. This was resolved and the links are now working correctly
