### ISSUE TITLE
document procmon 3.52 release

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/sysinternals#170]
can you please document the procmon 3.52 release? thats the one that is currently at https://download.sysinternals.com/files/ProcessMonitor.zip

while you are at it, maybe you can influence someone to please put a version number on the download link? or better yet... host the releases here on github ;-)

**Comment by lukekim** [comment]
Thanks for the feedback!

For releases, great suggestion, we are taking it under consideration.

**Comment by beerisgood** [comment]
*push*

Site still list 3.50 as latest version - even on the https://docs.microsoft.com/en-us/sysinternals/ "News site"

Also yes, please include versionstring in zip

**Comment by analyze-v** [comment]
Hi Beerisgood. 
I see that this is still an issue so have just updated this today. Please reopen if there are any further issues.

Cheers

Mark
