### ISSUE TITLE
PDF download is broken

### ISSUE THREAD

**Issue by PatrickWayland** [MicrosoftDocs/sysinternals#174]
https://docs.microsoft.com/en-us/sysinternals/opbuildpdf/toc.pdf?branch=live

something seems to be wrong with the PDF builder

**Comment by lukekim** [comment]
Thanks for reporting this, we'll take a look.

**Comment by v-kents** [comment]
@lukekim Begged, pleaded, and I think it's working now. Can you confirm for me? https://docs.microsoft.com/en-us/sysinternals/opbuildpdf/toc.pdf?branch=live

**Comment by analyze-v** [comment]
Thanks Kent. Seems to be working correctly now. Closing
