### ISSUE TITLE
Handle V4.21 cannot match fully specified file name anymore

### ISSUE THREAD

**Issue by kpwi** [MicrosoftDocs/sysinternals#175]
The versions V4.11 and V4.21 behave differently. Whereas 4.11 does find the PID of a file given (fully specified), V4.21 fails to do so:

**V4.11:**

> C:\Temp> handle_v411.exe -u AFX5723.tmp
> 
> Nthandle v4.11 - Handle viewer
> Copyright (C) 1997-2017 Mark Russinovich
> Sysinternals - www.sysinternals.com
>
> Skdaemon.exe       pid: 10044  type: File          DOMAIN\user.name          224: C:\Temp\AFX5723.tmp

**V4.21:**
> C:\Temp> handle_v421.exe -u AFX5723.tmp
> 
> Nthandle v4.21 - Handle viewer
> Copyright (C) 1997-2018 Mark Russinovich
> Sysinternals - www.sysinternals.com
> 
> No matching handles found.

_**but**_ if 4.21 gets only a part of the filename, it will find the corresponding handle!
> C:\Temp> handle_v421.exe -u AFX5723.tm
> 
> Nthandle v4.21 - Handle viewer
> Copyright (C) 1997-2018 Mark Russinovich
> Sysinternals - www.sysinternals.com
>
> Skdaemon.exe       pid: 10044  type: File          DOMAIN\user.name          224: C:\Temp\AFX5723.tmp

**Comment by lukekim** [comment]
Thanks for reporting, we are investigating the issue.

**Comment by analyze-v** [comment]
Thanks for reporting. I confirmed that this was a regression with 4.21 and have identified and resolved the issue. We will publish an update soon.

MarkC (MSFT)
