### ISSUE TITLE
Two copies of DebugView.exe in SysinternalsSuite.zip

### ISSUE THREAD

**Issue by SiloReed** [MicrosoftDocs/sysinternals#181]
When I extract the files in the April 23, 2019 released of SysinternalsSuite.zip, 7-zip displays a message that Dbgview.exe already exists
![image](https://user-images.githubusercontent.com/22893941/57875086-0e6e4c80-77e0-11e9-9630-659daeeb4189.png)

![image](https://user-images.githubusercontent.com/22893941/57875031-eaab0680-77df-11e9-9fbe-36198c47bc8a.png)

**Comment by lukekim** [comment]
Thanks for reporting this, we are fixing this.

**Comment by analyze-v** [comment]
Confirmed today that this has now been resolved so closing.
