### ISSUE TITLE
Autoruns / Space in executable path to hide from autoruns

### ISSUE THREAD

**Issue by mschilt** [MicrosoftDocs/sysinternals#185]
Looks like autoruns can be fooled by inserting a space in a executable path since Command and Arguments attribute get concatenated with a space in between. Interesting corner case but would be great if autoruns would check for this condition.

Details: 
TL;DR; Creating a scheduled task with a space in the file path will “hide” the executable from Autoruns. The file path is split on the space, the first part becomes the scheduled task’s command and the second part is treated as the command’s arguments. Autoruns uses the command as the image (executable) path for scheduled tasks. Tested on Windows 7, 2012, and 10. The task only ran on Windows 2012 and 10.

https://medium.com/@jdferrell3/scheduled-task-command-with-space-hides-the-file-from-autoruns-1c7bfe38a67c

**Comment by lukekim** [comment]
Thanks for reporting this, we've added it to our backlog.
