### ISSUE TITLE
Process Explorer: crashes when environment variable name length is 264 characters or more

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#186]
To reproduce the bug, set environment variable in cmd.exe and open Process Properties->Environment tab for the process
set nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn=Crash

**Comment by analyze-v** [comment]
Thank you for reporting. I have added this to the backlog and will get it resolved as soon as possible
MarkC (MSFT)

**Comment by analyze-v** [comment]
Quick update. We now have a fix for this and will be publishing soon. Closing

**Comment by AndreyBazhan** [comment]
Thank you, Mark!

**Comment by analyze-v** [comment]
Hi Andrey
Quick update to let you know that this has now been resolved and we will be publishing an update soon. I have added the other issues you reported to the backlog and will recommend that we bring them into the sprint next month during our next monthly backlog review.

Thanks again for reporting these issues.

Mark

**Comment by AndreyBazhan** [comment]
Hi Mark
Great! Thank you very much for letting me know, I very much appreciate it!
