### ISSUE TITLE
Process Explorer: Process Properties->Performance tab displays incorrect numbers

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#187]
Process Properties->Performance tab displays incorrect numbers when data is 2GB or more.
![ProcExpNumbers](https://user-images.githubusercontent.com/12948835/58436957-88e87780-80d0-11e9-9030-6d86e2d0fc4a.PNG)

**Comment by lukekim** [comment]
Thanks for reporting this, we'll take a look.

**Comment by analyze-v** [comment]
Added to backlog. Closing here
