### ISSUE TITLE
Process Explorer: Process Properties->Performance tab performance issue

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#188]
When you're opening Process Properties dialog (Performance tab) for a process that has a big working set (5-10 GB) it appears with a delay (a few seconds) and increases CPU usage by ~20-25%.

This is the test program that shows the root cause of the issue: https://gist.github.com/AndreyBazhan/1b984fac80e79bb17c03d4a8fc981384

To reproduce the issue, run Testlimit64.exe -d 1000 -c 10 before running the test program.

**Comment by lukekim** [comment]
Thanks for reporting this, we will take a look.

**Comment by analyze-v** [comment]
Have added to the backlog so closing here
