### ISSUE TITLE
Process Explorer: could make system unresponsive

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#189]
I've reported this issue in 2014 on Sysinternals forum, but it's not fixed yet.
Root cause analysis: http://www.andreybazhan.com/process-explorer-system-hang.html
![ProcExp](https://user-images.githubusercontent.com/12948835/58437512-ee3d6800-80d2-11e9-9b7f-33e38b6c8096.png)

**Comment by lukekim** [comment]
Thanks for reporting this, we'll take a look.

**Comment by analyze-v** [comment]
Have added to backlog.
