### ISSUE TITLE
Portmon Error 2 on POSReady7

### ISSUE THREAD

**Issue by Almagnus1** [MicrosoftDocs/sysinternals#190]
I'm trying to troubleshoot a serial device attached to a POS [Point Of Service] terminal running POSReady7 SP1 x64 (which is basically Win7 with additional Windows Embedded stuff), and this would be a phenomenal tool to use, however, whenever I try to launch it I'm getting Error 2.

I have reproed this issue by installing POSReady7, optionally turning on the page file, and then updating to current going by Windows Update.  As an FYI, if you have a KMS server on your network, you should probably use the Volume Licensed version of POSReady7 as that makes activation dead simple.

Any help is greatly appreciated.

**Comment by lukekim** [comment]
Thanks for reporting this, we'll take a look.

**Comment by analyze-v** [comment]
Added to backlog.
