### ISSUE TITLE
Sysmon: Feature Request | Process Creation Flags in Event 1

### ISSUE THREAD

**Issue by mschilt** [MicrosoftDocs/sysinternals#206]
Process Hollowing is still a widely used technique that is used to evade detection. 
Having process creation flags would allow us to detect processes that have been started with CREATE_SUSPENDED. Besides debuggers (and hollowing) I cannot think of any good reasons to start a program in a suspended state..

**Comment by analyze-v** [comment]
Thanks for the suggestion. Have added to the backlog for review at the next backlog review meeting
