### ISSUE TITLE
WSL的问题。

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/sysinternals#207]
procexp.exe获取不到进程的IAMGE，如：[连到系统上的设备没有发挥作用。]。
但是procmon能监控到，如：C:\Users\Administrator\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState\rootfs\usr\bin\top

procmon.exe监控到的文件操作为<Unknown : 70 >

望改进，与时俱进。

https://correy.webs.com

**Comment by kouzhudong** [comment]
C:\Users\Administrator>ver

Microsoft Windows [版本 10.0.18917.1000]

**Comment by analyze-v** [comment]
Apologies for the delay in responding but we had to have this translated. Have added to the backlog and will raise at the next backlog review
