### ISSUE TITLE
no csv/xml or json output in handle.exe? 

### ISSUE THREAD

**Issue by finBitorg** [MicrosoftDocs/sysinternals#210]
Please add support for csv / xml or json output

**Comment by finBitorg** [comment]
Same issue with ListDlls. Both great utilities but lack of structured output makes it harder to script.

**Comment by analyze-v** [comment]
Thanks for the suggestion. Have added this to the backlog and will raise at the next backlog review.

**Comment by czechnology** [comment]
Same request from me about the sigcheck tool. I ended up parsing the modified output as YAML but needs a lot of hacks to make it work. The CSV output is not very usable for nested structures like here.
JSON (preferably) or XML would be great.
Thanks for your hard work on these tools!
