### ISSUE TITLE
SysMon: Feature request: Logging of DNS Response TTL

### ISSUE THREAD

**Issue by OevreFlataeker** [MicrosoftDocs/sysinternals#211]
Starting with Sysmon v10 which is a huge step forward. Thank you very much for this!
For even better detection of C2 traffic communication (e.g. CobaltStrike) I'd would be perfect to have some metadata logged in the Type 22 events like e.g. the TTL of the response.
Looking at some PCAPs the very short TTLs for this kind of traffic (in that case TTL=1s!) was a very good indicator.
So, if you could add another Event-Attribute like "TTL" or "Metainfo" this would be great!

**Comment by analyze-v** [comment]
DNS logging uses ETW which doesn't give us access to the IP header. Thus while this is a great suggestion and I can see it being a useful field for IOCs. we don't have this value.

**Comment by analyze-v** [comment]
Sorry I misread this earlier. We use ETW for the DNS Logging but currently this doesn't provide the TTL so we can't include it.
