### ISSUE TITLE
Sigcheck lacks proxy support for Vt lookups

### ISSUE THREAD

**Issue by finBitorg** [MicrosoftDocs/sysinternals#212]
Sigcheck lacks proxy support for Vt lookups

**Comment by finBitorg** [comment]
tried "set HTTP_PROXY = proxyurl"  and  "set HTTPS_PROXY = proxyurl"

**Comment by analyze-v** [comment]
Thanks for this. I have added it to the backlog and will raise it at the next backlog review

**Comment by mschilt** [comment]
It would be very valuable to have proxy support in sigcheck since many enterprise setups only allow internet connections over a proxy.
Not only VT lookups are not working but also CRL checks do not seem to work when you are behind a proxy (even winhttp).

**Comment by analyze-v** [comment]
Hi Manuel
This is already on our backlog for both Sigcheck and Autoruns. I have flagged both for consideration at our next backlog review.

Regards

Mark

**Comment by rhalade** [comment]
I see this issue as closed. What is the resolution or is it duplicate of some other backlog you have?
