### ISSUE TITLE
Filter by Title not refreshing correctly

### ISSUE THREAD

**Issue by analyze-v** [MicrosoftDocs/sysinternals#217]
The “filter by title” text box doesn’t work after downloading a tool.
Repro:
•	Go to Sysinternals.com
•	In the “filter by title” text box, type psexec; click on “PsExec” in the returned results  page navigates to https://docs.microsoft.com/en-us/sysinternals/downloads/psexec as expected.
•	Click the link to download PsTools, and download to the default location.
•	In the “filter by title” text box, type streams; click on “Streams” in the returned results
o	Expected result: page navigates to Streams download page
o	Actual result: page doesn’t change

**Comment by analyze-v** [comment]
This appears to affect Internet Explorer only as it works correctly on Firefox and Edge

**Comment by foxmsft** [comment]
This should be working by now, closing.
