### ISSUE TITLE
DHCP Logging Feature Request

### ISSUE THREAD

**Issue by c2defense** [MicrosoftDocs/sysinternals#218]
Feature Request:
Like DNS Logging, DHCP logging within Microsoft is only possible when the Debug/Analytical log is turned on which in turn outputs the ETL/ETW events that can't be forwarded via built-in Windows Event Collection (WEC).  

Now that with version 10 we see the ETW can be leverage by Sysmon, I would request that Sysmon be able to log DHCP client-server events for the Windows Servers that have that role turned on.

**Comment by analyze-v** [comment]
Hi this one is actually already on the backlog. Will update once it has been implemented.
