### ISSUE TITLE
Sysmon Modular Rule Feature Request

### ISSUE THREAD

**Issue by temp466** [MicrosoftDocs/sysinternals#222]
Allow the ability to create modular signature-like "rules" in the Sysmon configuration file. In the below example Sysmon will log "powershell.exe" if it is spawned by "cmd.exe".

```
<RuleGroup name="group 1" groupRelation="and">
	<ProcessCreate onmatch="include">
		<Image condition="end with">powershell.exe</Image>
		<ParentImage condition="end with">cmd.exe</ParentImage>
	</ProcessCreate>
</RuleGroup>
.....

```
If I attempt to run calc.exe from cmd.exe no event is generated. I've then attempted to run powershell from a desktop shortcut where the parent process would be explorer.exe and no log has been generated. Then I've turned on the following config:

```
<RuleGroup name="group 1" groupRelation="and">
	<ProcessCreate onmatch="include">
		<Image condition="end with">powershell.exe</Image>
		<ParentImage condition="end with">cmd.exe</ParentImage>
		<Image condition="end with">cmd.exe</Image>
		<ParentImage condition="end with">explorer.exe</ParentImage>
	</ProcessCreate>
</RuleGroup>
.....
```

This time if I run powershell through the shortcut on my Desktop it creates an alert. This happens because the below line is present but it would be better if a log was only generated when explorer.exe was the parent of cmd.exe.

`<ParentImage condition="end with">explorer.exe</ParentImage>`

Is there a way/future plans to segregate rules so in the case of the second config the following happens:

A log for powershell.exe is only created when cmd.exe is the parent.
A log for cmd.exe is only created when explorer.exe is the parent.

This would allow for very granular rules that would heavily reduce unwanted noise generated by Sysmon. The ideal scenario would be to have a single rule that could have its own include and exclude fields. Take this configuration:

```
<RuleGroup name="group 1" groupRelation="and">
	<ProcessCreate onmatch="include">
		<Image condition="end with">powershell.exe</Image>
		<Image condition="end with">cmd.exe</Image>
		<ParentImage condition="end with">cmd.exe</ParentImage>
	</ProcessCreate>
	<ProcessCreate onmatch="exclude">
		<ParentImage condition="end with">explorer.exe</ParentImage>
	</ProcessCreate>
</RuleGroup>
```

If I only wanted to ignore explorer spawning powershell.exe and not cmd.exe it cannot be done. However, an ideal configuration could look like this

```
Rule 1
ProcessCreate include
    image=powershell.exe
    image=cmd.exe
    parentimage=winword.exe
ProcessCreate exclude
    commandline=
    commandline=

rule 2
ProcessCreate include
    image
    image
    parentimage
ProcessCreate exclude
    image
    image
    commandline
```

**Comment by analyze-v** [comment]
Hello
thanks for the comprehensive list. This is indeed high on our backlog and in fact we've discussed a schema very similar to the one that you are proposing which we would essentially implement using nested rule groups or similar.

One of the main challenges we face is that flexibility comes at a price. Rule processing is a major chokepoint so we have to balance utility and performance. Nevertheless we recognise that many of our users want this level of granularity and are looking to see what we can do. 

I'll contact you once we have something in progress which should hopefully be this month so that you can provide feedback early in the development process..

MarkC (MSFT)

**Comment by analyze-v** [comment]
Hello
if you are still interested in this can you contact me offline at syssite@microsoft.com. I have recently implemented something similar to this and would like to discuss it with you to ensure it meets your requirement.

MarkC (MSFT)
