### ISSUE TITLE
[RAMMap] BASH/PowerShell Support for standy memory zeroing.

### ISSUE THREAD

**Issue by frenchiveruti** [MicrosoftDocs/sysinternals#224]
I wanted to know if there's support for something like this.  
Most of the time I have to open RAMMap just for zeroing the standby memory that windows manages so poorly.  
My question is if there's something like:
`RAMMap.exe --zerostandby  `
That would just cleanup the standby memory.  
Thanks.

**Comment by analyze-v** [comment]
We've had lots of requests for command line switches to RAMMAP and it's already on our backlog. Will try to get this done soon.

**Comment by frenchiveruti** [comment]
That's ok, I understand as it's a free software, feel free to close the issue or tag it accordingly.  
I can't wait for this feature, a just one click standby memory cleanup script would be a great thing to have haha.

**Comment by analyze-v** [comment]
Hello
Actually since I was already making some changes to RAMMAP I added this earlier today. Will let you know once the change has been published.

MarkC (MSFT)

**Comment by frenchiveruti** [comment]
Ha! That was fast 😃   
Ok, thanks!

**Comment by kelleyma49** [comment]
Has this been published? I don't see this option in the 2020.7.15 tools:
![image](https://user-images.githubusercontent.com/2152684/91477952-f5ae6c80-e853-11ea-94f1-8843e527c942.png)

**Comment by frenchiveruti** [comment]
I'd like to know too...

**Comment by aslamperumani** [comment]
**cd C:\Users\aslamperumani\Downloads\RAMMap && RAMMap -Et**

Open **CMD** (Run as Administrator) > enter the command "**cd C:\Users\jazim\Downloads\RAMMap && RAMMap -Et**" > Run the command

cd <enter your RAMMap path> and && RAMMap -Et

This is the command for end standby or clear ram cache

Rammap Bash / Command Line clear ram cache

**Comment by SMWkda** [comment]
![{49E79A77-BE91-4C21-BCF2-188C72CEFD64}](https://github.com/user-attachments/assets/15b8d60d-2d4c-4105-a24d-67f21e1df1a8)
Task Scheduler also can automate this process
