### ISSUE TITLE
BGInfo Version number

### ISSUE THREAD

**Issue by Syberdoor** [MicrosoftDocs/sysinternals#225]
The Page for BgInfo (https://docs.microsoft.com/en-us/sysinternals/downloads/bginfo aka https://github.com/MicrosoftDocs/sysinternals/blob/live/sysinternals/downloads/bginfo.md) has v4.26 as the Version number although the actual version of the download is v4.27.

**Comment by analyze-v** [comment]
Thanks for reporting. I will get this updated as soon as possible.

**Comment by analyze-v** [comment]
I just updated this now. Thanks again for reporting.
