### ISSUE TITLE
Process Explorer: move handles and dlls view into process properties dialog

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#230]
Could you please move handles and dlls view into process properties dialog, so user would have the ability to see handles and dlls in different processes simultaneously?

**Comment by analyze-v** [comment]
Hi Andrey
sorry for the delay in responding. Our backlog review was cancelled last month but the next one is coming up in the next week so I have added this to the backlog and flagged it for consideration.
Regards

Mark

**Comment by AndreyBazhan** [comment]
Hi Mark
Thank you!
