### ISSUE TITLE
Autoruns: File not found in Image Path in scheduled tasks

### ISSUE THREAD

**Issue by oppiman** [MicrosoftDocs/sysinternals#231]
An entry in scheduled tasks like C:\windows\system32\cmd.exe /c req query "HKLM\..." will be displayed in autoruns as File not found: reg.
Similar an entry like powershell -executionpolicy bypass "&'c:\program...'" will be seen as File not found: bypass.
Can be reproduced in version 13.96.

**Comment by analyze-v** [comment]
Hello
sorry for the delay in responding. I just tried this and I'm seeing something squiffy but not the same thing you are. Could you contact me offline at syssite@microsoft.com so that I can follow up with you and get this resolved

Mark Cook (MSFT)

**Comment by analyze-v** [comment]
Added to backlog. Closing here
