### ISSUE TITLE
Issue: ASCII-Extended Characters Rendering in Error Message[s]

### ISSUE THREAD

**Issue by felsokning** [MicrosoftDocs/sysinternals#232]
**Problem:**
Windows has locales that use extended character sets. Error strings returned by translated hResults (e.g.: AccessDenied) are attempted to be displayed in the standard ASCII set and produce unreadable characters (e.g.: ASCII != ASCII-Extended).

In this specific use-case, Windows is set to Swedish language/locale.

**Steps to reproduce:**
PowerShell script

```
$Source = @"
namespace Test
{
    using System.Diagnostics;

    public class Processing
    {
        public static void CreateProcess()
        {
                        ProcessStartInfo StartInfo = new ProcessStartInfo
                        {
                            Arguments = string.Format("/K C:\\SysInternals\\sdelete64.exe -p 3 \"{0}\"", "C:\\Program Files\\Common Files\\microsoft shared\\ink\\ipsdeu.xml"),
                            CreateNoWindow = false,
                            FileName = "CMD.EXE",
                            UseShellExecute = true,
                            Verb = "runas",
                            WindowStyle = ProcessWindowStyle.Maximized,
                        };

                        Process deletionProcess = Process.Start(StartInfo);

        }

    }

}
"@

Add-Type -TypeDefinition $Source -Language CSharp

[Test.Processing]::CreateProcess()
```

Resultant Window

```
SDelete v2.02 - Secure file delete
Copyright (C) 1999-2018 Mark Russinovich
Sysinternals - www.sysinternals.com

SDelete is set for 3 passes.
C:\Program Files\Common Files\microsoft shared\ink\ipsdeu.xml...
Error opening C:\Program Files\Common Files\microsoft shared\ink\ipsdeu.xml for delete:
┼tkomst nekad.     <-- Note the incorrect character at the beginning.

No files/folders found that match C:\Program Files\Common Files\microsoft shared\ink\ipsdeu.xml.
```

**Work-arounds:**
None known, as of yet.

**Expected Results:**
The error message should be ```Åtkomst nekad.``` [Proof](https://support.microsoft.com/sv-se/help/2623670/access-denied-or-other-errors-when-you-access-or-work-with-files-and-f)

**Notes of Interest:**
This probably occurs for all non-English error message[s] returned, in which all of the characters are not in the standard ASCII set (e.g.: French, German, etc.).

**Comment by analyze-v** [comment]
Thanks for posting this. We have an item already in the backlog related to the way that sigcheck and a couple of the other tools display internationalized strings but I wasn't aware of this particular issue. I have added it to the backlog and flagged it for discussion at next week's backlog review

MarkC (MSFT)
