### ISSUE TITLE
sdelete odd behaviour

### ISSUE THREAD

**Issue by vorgos** [MicrosoftDocs/sysinternals#233]
Running v2.02 and when cleaning with,

sdelete -c \<drive no\>

I get pass 0 at >100MB/s then pass 1 at less than half the speed. Help screen says default number of passes is 1.

Based on speed, seems like pass 0 is zeroing while pass 1 might be writing random data.

Specifying drive letter instead of drive number seems to do only one pass.

thx.

**Comment by analyze-v** [comment]
Thanks for reporting this. Will investigate and get back to you

**Comment by dp250f** [comment]
I have seen this behavior with version 2.04:
When cleaning (-c) a specified drive number with 1 pass (-p 1), it does infinite passes when it is set to only do 1.
When zeroing (-z) a specified drive number with 1 pass (-p 1), it does one pass as it should.

**Comment by foxmsft** [comment]
We will address this in an upcoming release, thanks!
