### ISSUE TITLE
RamMap feature request: export table

### ISSUE THREAD

**Issue by ov2k** [MicrosoftDocs/sysinternals#235]
The tool is great, but sometimes the included filtering isn't quite enough.  A way to export a table (e.g., physical pages) to some standard spreadsheet or database file format (e.g., .csv) would be really useful for those of us who don't know how to parse a .rmp file and the embedded PFN database.

**Comment by analyze-v** [comment]
Thanks for the suggestion. I have added this to the RAMMAP backlog

Mark Cook (MSFT)

**Comment by chvogel** [comment]
So this feature request was marked as "completed" 5 years ago, but I cannot find any export function in the latest version of RAMMap (v1.61 from May 2022).
I also tried Ctrl-C with a list view focused, hoping for a hidden copy function, but to no avail.

Was this actually ever implemented?

----

**Background:**
I am trying to understand why a large chunk of memory is being used for Mapped Files (active, not standby).
The File Summary tab only shows a few medium sized files and a lot of small files with active mappings.
Just from looking at the top of the list, it doesn't seem like the files would add up to the total size of active mapped files, but there are so many entries that this could very well be misleading.
I would really like to copy the data to Excel and dig down more, for example grouping by path to see any patterns.
