### ISSUE TITLE
Process Monitor v3.52 issue

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/sysinternals#242]
在IRP_MJ_DIRECTORY_CONTROL->QueryDirectory的操作中，
发现没有FILE_INFORMATION_CLASS FileInformationClass这个消息内容。

希望加上。

https://correy.webs.com

**Comment by analyze-v** [comment]
Thanks for reporting. I have added this to the Procmon backlog.

**Comment by analyze-v** [comment]
Hello
could you clarify what it is you want (preferably in English). Was it just the IrpSp->Parameters.QueryDirectory.FileInformationClass value that you believe is missng ?

MarkC (MSFT)

**Comment by kouzhudong** [comment]
yes.

**Comment by analyze-v** [comment]
Great thank you. I've added this and it will be available in the version 3.53 which we will publish soon
MarkC(MSFT)
