### ISSUE TITLE
Requesting option in procexp to scale CPU usage to 100% = 1 core

### ISSUE THREAD

**Issue by gsuberland** [MicrosoftDocs/sysinternals#243]
I am running 2x Xeon 8276L in my workstation and I have found that Task Manager is practically useless for understanding CPU usage on a per-process level when that process is only running a single-threaded load, because the usage percentage ends up being rounded to either 0 or 1 in the CPU column.

Process Explorer is marginally better in this regard because it provides precision up to two decimal places, but on a system with 112 logical cores it only shows around 0.89% usage for a single-core load, making it quite difficult to mentally quantify the values unless you can quickly multiply by 112 in your head (I, personally, cannot).

I would like the option to be able to switch the CPU Usage column to display 100% for a fully-utilised core, and numbers beyond 100% for multi-threaded loads, much like Linux has done traditionally with tools like `top`. Precision beyond an integer would not be required in this mode.

I have also toyed with the idea of requesting a "number of utilised cores" column, which would display the total number of logical processors upon which the process has been scheduled since the last refresh, but I am unsure if the requisite data is available from process information APIs and perfromance counters.

Thank you.

**Comment by analyze-v** [comment]
This is a great suggestion. I've added it to our product backlog and flagged it for consideration at the next backlog review with Mark R. since he approved all feature requests. 

As I understand it you're effectively asking for Irix mode. Was it just a %usage you were proposing or did you want to be able to filter the graphs to show the activity of just that process on each CPU too (assuming this is possible)?

MarkC (MSFT)

**Comment by gsuberland** [comment]
Thanks for the quick response! Yes, Irix mode is exactly it - I hadn't heard that term before.

I originally did just think about total processor usage, but filtering the graphs by process would also be useful if the data is available and it's not an excessive amount of work to get the feature in.

**Comment by HarukaMa** [comment]
Hi - is this issue in `wontfix` status considering it is closed without the function actually being implemented?
