### ISSUE TITLE
Azure Service Fabric Installation with Sysmon Causes CPU Exhaustion

### ISSUE THREAD

**Issue by klemaned** [MicrosoftDocs/sysinternals#260]
1. New Server 2016 Install (No updates required)

2. Install Latest Sysmon with config:
`<Sysmon schemaversion="4.22">
	<HashAlgorithms>md5,sha256</HashAlgorithms>
	<CheckRevocation/>
	<EventFiltering>
	<RuleGroup name="" groupRelation="or">
		<FileCreateStreamHash onmatch="include">
		</FileCreateStreamHash>
	</RuleGroup>
	</EventFiltering>
</Sysmon>`

3. Download Service Fabric Installation Package to 2016 (https://go.microsoft.com/fwlink/?LinkId=730690)

4. Execute ".\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath .\ClusterConfig.Unsecure.DevCluster.json -AcceptEULA" from Downloaded Microsoft.Azure.ServiceFabric.WindowsServer.* directory

5. Wait approximately 5 minutes for c:\ProgramData\SF\ReplicatorLog\replicatorshared.log to be created and CPU will become exhausted.

Please let me know if it would be better to open a case with Microsoft Support, but I was unable to find an appropriate category to open it under.

**Comment by analyze-v** [comment]
Hello
thanks for reporting. I have added it to our backlog and will review with Mark R at the next backlog review later this month.  Note that like the other Sysinternals tools, there is no formal support for Sysmon. However Mark tends to prioritize Sysmon issues highly so I suspect this will be something he will want us to jump on.

Regards

Mark Cook (MSFT)
