### ISSUE TITLE
WHOIS v1.21: Client doesn't support all IP addresses (actual some types of whois queries - invalid request)

### ISSUE THREAD

**Issue by krjdev** [MicrosoftDocs/sysinternals#262]
Hi,

The client doesn't support some types of formatted queries.
Have tried the downloaded version 1.21:

```
$ .\whois.exe 62.46.172.92

Whois v1.21 - Domain information lookup
Copyright (C) 2005-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

Connecting to AT.whois-servers.net...

% Copyright (c)2020 by NIC.AT (1)
%
% Restricted rights.
%
% Except  for  agreed Internet  operational  purposes, no  part  of this
% information  may  be reproduced,  stored  in  a  retrieval  system, or
% transmitted, in  any  form  or by  any means,  electronic, mechanical,
% recording, or otherwise, without prior  permission of NIC.AT on behalf
% of itself and/or the copyright  holders.  Any use of this  material to
% target advertising  or similar activities is explicitly  forbidden and
% can be prosecuted.
%
% It is furthermore strictly forbidden to use the Whois-Database in such
% a  way  that  jeopardizes or  could jeopardize  the  stability  of the
% technical  systems of  NIC.AT  under any circumstances. In particular,
% this includes  any misuse  of the  Whois-Database and  any  use of the
% Whois-Database which disturbs its operation.
%
% Should the  user violate  these points,  NIC.AT reserves  the right to
% deactivate  the  Whois-Database   entirely  or  partly  for  the user.
% Moreover,  the  user  shall be  held liable  for  any  and all  damage
% arising from a violation of these points.

% ERROR - Invalid request


Connecting to )2020 by NIC.AT (1)                                       ...
Der angegebene Host ist unbekannt.
```

Same with the 64 Bit edition, also with admin privileges.
No issues with the same query on my other used OS'es (Linux, OpenBSD, FreeBSD).

**Edit:**
Also when using the following command structure:
```
$ .\whois.exe "62.46.172.92"
```

(Tested on Windows 10 Pro Version 1909 - Build 18363.535)

**Comment by krjdev** [comment]
Okay, interesting...

I have captured the query with wireshark. The used IP address is from my ISP. Seems **NIC.AT** doesn't supports the following query (See screenshot):
```
62-46-172-92.ADSL.HIGHWAY.TELEKOM.AT\r\n
```
<img width="753" alt="wireshark_whois_win10" src="https://user-images.githubusercontent.com/20015689/71927679-4de61080-3196-11ea-812b-77a3cef45513.png">

But it works with the Linux client with the follwoing formated query:
```
62.46.172.92\r\n
```

Anyway, could you please add support for this?

**Comment by analyze-v** [comment]
Hello
I just tried this and can confirm what you are seeing. I don't think this is necessarily related to the \r\n at the end of the query since the following fails 

whois64 62-46-172-92.adsl.highway.telekom.at

But the following is successful

whois64 telekom.at

I have added this to our backlog for review and fixing and will revert once we have an update

Mark Cook (MSFT)
