### ISSUE TITLE
Procdump doesnt capture dumps when passed 'exception type' to -f switch

### ISSUE THREAD

**Issue by fasigpt** [MicrosoftDocs/sysinternals#267]
I am trying to capture dump on a specific exception 
ex: 
System.StackOverflowException
procdump -e 1 -ma -f *System.StackOverflowException* app.exe

The above command doesnt generate any dump, however passing the exception code as below does work and it created a dump
procdump -e 1 -ma -f C00000FD.STACK_OVERFLOW app.exe

Is there a way to capture dump by passing exception message (System.StackOverflowException) ?

**Comment by analyze-v** [comment]
Could you contact me offline at syssite@microsoft.com and send me the full output from the exception message??

**Comment by analyze-v** [comment]
Never received a response to this so closing
