### ISSUE TITLE
bginfo corrupts the bgi file

### ISSUE THREAD

**Issue by massimo-sala** [MicrosoftDocs/sysinternals#268]
Hi
A simple BGI file with 7 custom fields is corrupted by bginfo.
It seems to me bginfo writes (and corrupts) the file when there is any problem processing the custom fields.

> Windows 10.0.18363.592
> Bginfo 4.28

[BGinfo.zip](https://github.com/MicrosoftDocs/sysinternals/files/4399402/BGinfo.zip)

**Comment by analyze-v** [comment]
This is already on our backlog so closing
