### ISSUE TITLE
BGinfo new feature: save options as XML, not custom BGI files

### ISSUE THREAD

**Issue by massimo-sala** [MicrosoftDocs/sysinternals#269]
Hi @analyze-v 
First of all, compliments for this useful tool.

IMHO the custom BGI file format is a no-go:
1) time wasting to have to open BGinfo every time to read / edit the file
2) cannot source-control these files
3) cannot modify these files using automation tools

Please can you suppport load and save from XML ?

**Comment by analyze-v** [comment]
I have added this to the backlog for review with Mark R. Closing
