### ISSUE TITLE
AdExplorer has   Trojan.Agent!MT0GiLQiUhU

### ISSUE THREAD

**Issue by aafliti** [MicrosoftDocs/sysinternals#274]
AdExplorer has   Trojan.Agent!MT0GiLQiUhU by VirusTotal

No words ...

 MD5 3ce4429e50035fa850d5879ea8521c87
SHA-1 f7e154e519ca0b593a55e980715a3a4bbb2d391d
SHA-256 97ef5001c225a869ae739c15aab1e067b66ce85250ff4d3c265bbfaf09ac8308
Vhash 0e2b0396731653b9d5f07ed3788398dc
SSDEEP 6144:26XTUSzUxjz9m4LZ6ZzmeSg6R5hsnTaX4aWNdlVUOr2XWF4/9OMP:26XTUSANc4LZ8zmeE5oaoaW7lVU6TFK/
File type ZIP
Magic Zip archive data, at least v2.0 to extract
File size 243.48 KB (249327 bytes)
F-PROT appended, Unicode

**Comment by analyze-v** [comment]
It's quite common for one or two AV scanners to report a FP on a benign file.  In this instance it looks like it has already been resolved.
