### ISSUE TITLE
Sysmon Feature Request: "is any" filter condition

### ISSUE THREAD

**Issue by murphnomer** [MicrosoftDocs/sysinternals#278]
The new "contains any" filter condition is a great addition, but is difficult to use with numerical items like ports (e.g. if I want to include port 389 but not 3389 in a rule) without making the rule too broad.

If we had an "is any" filter condition so that we could exactly specify a list of values to be included in the rule it would be very helpful.

**Comment by markrussinovich** [comment]
Great suggestion. Look for this in the next update.
