### ISSUE TITLE
Sysmon 11 error during installation (network connections)

### ISSUE THREAD

**Issue by yukh1402** [MicrosoftDocs/sysinternals#285]
**Long story short**
I would like to install sysmon version 11 including network connections by entering following command `Sysmon64.exe -i -n -accepteula`. Unfortunately an error occurs if `-n` is defined in the command.

**Expected behaviour**
I expect sysmon to be installed including network connections.

**Actual behaviour**
After entering `Sysmon64.exe -i -n -accepteula` in cmd the installation process starts by displaying the current sysmon version, but suddenly it just aborts. I found an error message in the windows application logs

`Faulting application name: Sysmon64.exe, version: 11.0.0.0, time stamp: 0x5ea6faf3
Faulting module name: Sysmon64.exe, version: 11.0.0.0, time stamp: 0x5ea6faf3
Exception code: 0xc0000005
Fault offset: 0x000000000000e433
Faulting process ID: 0x1c48
Faulting application start time: 0x01d6284033be8681
Faulting application path: C:\Users\name\Desktop\sysmon\Sysmon 11\Sysmon64.exe
Faulting module path: C:\Users\name\Desktop\sysmon\Sysmon 11\Sysmon64.exe
Report ID: 9f106f59-fc82-4908-b8e4-4216101530d4
Faulting package full name: 
Faulting package-relative application ID: `

**System**
Windows 10.0.18362 .0
Sysmon 11

**Comment by darthje** [comment]
I have the same problem. I tried several computers and got the same error.

**Comment by jokezone** [comment]
@yukh1402 according to [this tweet](https://twitter.com/CipherMonger/status/1257367319434715138) about the -n switch no longer working on Sysmon v11, Mark Russinovich confirmed that this is intended behavior. So you can install Sysmon without the -n switch and then enable Network monitoring using a configuration file.

**Comment by darthje** [comment]
Thanks a lot for the info ;)

**Comment by analyze-v** [comment]
Yes this is correct.
