### ISSUE TITLE
whois.exe

### ISSUE THREAD

**Issue by cjx82630** [MicrosoftDocs/sysinternals#291]
Hi, if I type in "gadhx.cn",  it will "Connecting to adhx.cn" in the end and freezed for a few minutes.
If I type in "adhx.cn",  it will "Connecting to dhx.cn" in the end.
It also happens with "ruten.com.tw", it will "Connecting to uten.com.tw" in the end.

```
C:\Users\ADMIN>whois gadhx.cn

Whois v1.21 - Domain information lookup
Copyright (C) 2005-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

Connecting to CN.whois-servers.net...

Domain Name: gadhx.cn
ROID: 20200218s10001s25431501-cn
Domain Status: ok
Registrant ID: 22cn191227zijqza
Registrant: 閲戠強
Registrant Contact Email: ys33com@gmail.com
Sponsoring Registrar: 娴欐睙璐拌窗缃戠粶鏈夐檺鍏徃
Name Server: ns2.22.cn
Name Server: ns1.22.cn
Registration Time: 2020-02-18 09:04:18
Expiration Time: 2021-02-18 09:04:18
DNSSEC: unsigned

Connecting to adhx.cn...
```

**Comment by lukekim** [comment]
Thanks, as this is the documentation GitHub, please submit the question to our community support channel https://forum.sysinternals.com - closing this Issue.
