### ISSUE TITLE
It's not possible to unload the procmon/Process Monitor driver without a reboot

### ISSUE THREAD

**Issue by ganego** [MicrosoftDocs/sysinternals#302]
When starting Process Monitor, the program loads a driver `C:\Windows\system32\Drivers\PROCMON24.SYS`. Even after closing the program, the driver is still active.  
This will be a problem when running software that requires the BattleEye anti-cheat software, as BattleEye cannot check this driver or unload it.

See: https://superuser.com/questions/1346125/how-can-i-unload-the-process-monitor-driver-without-restarting

When using Windows 10, even a "normal" (quick) reboot won't help and you have to manually enforce a "real" reboot.

**Comment by foxmsft** [comment]
Hey, thanks for the report. Keep in mind that this repo is only dedicated to documentation.

Please head over to [the Sysinternals TechNet forum](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals) for more support, both community-driven and from the team, as that place is the recommended contact for troubleshooting and bug reports.

I'll close this issue here.

**Comment by karl-police** [comment]
> Hey, thanks for the report. Keep in mind that this repo is only dedicated to documentation.
> 
> Please head over to [the Sysinternals TechNet forum](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals) for more support, both community-driven and from the team, as that place is the recommended contact for troubleshooting and bug reports. I have [created a question there](https://social.technet.microsoft.com/Forums/en-US/984d06af-3dae-43fe-b86f-f46dbcef3a77/its-not-possible-to-unload-the-procmonprocess-monitor-driver-without-a-reboot?forum=procmon) for this issue, feel free to reply there so that you get notifications from new activity.
> 
> I'll close this issue here.

NO HELP US

thanks :)

**Comment by karl-police** [comment]
> > Hey, thanks for the report. Keep in mind that this repo is only dedicated to documentation.
> > Please head over to [the Sysinternals TechNet forum](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals) for more support, both community-driven and from the team, as that place is the recommended contact for troubleshooting and bug reports. I have [created a question there](https://social.technet.microsoft.com/Forums/en-US/984d06af-3dae-43fe-b86f-f46dbcef3a77/its-not-possible-to-unload-the-procmonprocess-monitor-driver-without-a-reboot?forum=procmon) for this issue, feel free to reply there so that you get notifications from new activity.
> > I'll close this issue here.
> 
> NO HELP US
> 
> thanks :)
