### ISSUE TITLE
Not showing HKCU Autorun entry with malformed Unicode

### ISSUE THREAD

**Issue by lasrx** [MicrosoftDocs/sysinternals#310]
Autoruns 13.98 did not itemize a startup item that has invalid unicode.
![SysInternals](https://user-images.githubusercontent.com/9558779/93684868-50f30980-fa64-11ea-84b4-9e4a93340ea9.png)

Visible In Control Startup Items
![Control Panel Startup](https://user-images.githubusercontent.com/9558779/93683888-01acd900-fa64-11ea-8fa9-f356cdac3229.png)

Visible in PowerShell
![PowerShell Output](https://user-images.githubusercontent.com/9558779/93683848-feb1e880-fa63-11ea-8127-642e9069af18.png)
Get-CimInstance -ClassName Win32_StartupCommand |
  Select-Object -Property Command, Description, User, Location |
  Out-GridView

Semi-Visible in RegEdit
![Registry Viewer](https://user-images.githubusercontent.com/9558779/93683894-01acd900-fa64-11ea-8701-68d1098d2358.png)

**Comment by foxmsft** [comment]
Thanks for reporting.

Is that a legitimate Unicode entry? Does the software manage to run automatically?

**Comment by lasrx** [comment]
We don't believe this was legitimate unicode.  The software as far as we can tell did not run.

**Comment by foxmsft** [comment]
Not considering this one as an Autoruns limitation, rather as an underlying system limitation. Closing for now, please inquire further on [the support forum](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals) if you still run into issues related to this.
