### ISSUE TITLE
sigcheck not verify some files correctly

### ISSUE THREAD

**Issue by gregzakh** [MicrosoftDocs/sysinternals#311]
![screen](https://user-images.githubusercontent.com/19162617/94188025-397faa80-fec2-11ea-8f49-1ca6b72b75ed.png)

**Comment by foxmsft** [comment]
Funny find, did you just stumble into this?

**Comment by gregzakh** [comment]
> Funny find, did you just stumble into this?

Nope!

**Comment by foxmsft** [comment]
Thanks for the report, will release the fix with the next version.

**Comment by foxmsft** [comment]
Just an update, @gregzakh, this works as intended. That HTTP error response comes from a default IIS error file and it's signed by Microsoft and recognized by sigcheck through one of the `.cat` files shipped with Windows operating systems.
