### ISSUE TITLE
ClipboardCapture not working all the time

### ISSUE THREAD

**Issue by jakko10** [MicrosoftDocs/sysinternals#313]
I created this rule:
`<Sysmon schemaversion="4.40">
  <CaptureClipboard />
  <EventFiltering>
      <RuleGroup name="" groupRelation="or">
          <ClipboardChange onmatch="exclude">
          </ClipboardChange>
      </RuleGroup>
  </EventFiltering>
</Sysmon>`

Started sysmon with sysmon -i myconfigfile.cfg.xml
All good so far.
Then I discovered when I copy something to the clipboard locally on the machine like any random copy/paste, then capture clipboard works fine, the file will get created to c:\sysmon\clip-sid.

But, when I put something on the clipboard over the SSH connection, let's say I use something like this ´ssh myuser@x.x.x.x "set-clipboard -value 'my text'" then sysmon just ignores it even if I call the value by adding `get-clipboard` like:  ´ssh myuser@x.x.x.x "set-clipboard -value 'my text'; get-clipboard" I do get the clipboard content, but sysmon keeps ignoring. No event, nothing.

**Comment by foxmsft** [comment]
Thanks for reporting this - it's a current limitation of how clipboard monitoring works. Please direct any subsequent inquires to [the support forum](https://social.technet.microsoft.com/Forums/en-US/home?category=sysinternals), closing this issue.
