### ISSUE TITLE
Procmon没有监控到WSL的进程的DLL（SO）的加载。

### ISSUE THREAD

**Issue by kouzhudong** [MicrosoftDocs/sysinternals#315]
难道是因为微软没有提供这样的借口（回调）才导致的？

这里是指Load Image，而非文件监控（FASTIO_ACQUIRE_FOR_SECTION_SYNCHRONIZATION）。

**Comment by foxmsft** [comment]
Thank you for reporting this. There is a current limitation towards WSL processes among the various Sysinternals tools. Closing this here, support will keep being improved in future releases.
