### ISSUE TITLE
ADInsight: Any supported OSes supported by the application?

### ISSUE THREAD

**Issue by jricha34** [MicrosoftDocs/sysinternals#318]
Are there any supported OSes that support this tool? Been awhile since 2008 and Vista were supported. 

Windows 10 2004 doesn't seem to work with this tool. Doesn't capture LDAP and on exit a crash is detected and the system wants to debug it.

**Comment by foxmsft** [comment]
Good point. Considering renewing the tool for modern Windows versions right now. Will close this, stay tuned for upcoming Sysinternals releases.
