### ISSUE TITLE
Zoomit draw does not appear when share screen with MS Teams

### ISSUE THREAD

**Issue by BGFR** [MicrosoftDocs/sysinternals#324]
HI, i hope s.o. can help me with this issue.
I installed zoomit on windows10 Lenovo Thinkpad T420. It worked fine until I started an MS Teams and I was told that draw does not show on the desktops of the participants. Zoom function worked, but not the draw. I later reconfirmed that testing internally. 
 I was sharing a chrome tab with youtube video.
Then, to test I installed zoomit on another PC and hosted a test MS Teams meeting, sharing screen with Thinkpad T420, which was this time a participant. This time zoomit draw appeared on the participant screen.
I was googling a lot find similar issue shared, but no success....

**Comment by foxmsft** [comment]
Hi, please direct your support query towards [the Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/windows-sysinternals-misc-utilities.html) (the Sysinternals forums have recently transitioned there). It's the best source for feedback with regard to the tools or for community support.

**Comment by BGFR** [comment]
HI, thank you. Just for reference, i opened the same on Microsoft Q&A and i got similar answer,
