### ISSUE TITLE
config read bug in sysmon 12.03, relates to #282,#283

### ISSUE THREAD

**Issue by oppiman** [MicrosoftDocs/sysinternals#331]
I took the "simple config" out of "sysmon -? config" output:

Named it simple.xml, loaded it, works. 

Then I added a group to the config. Named the file simple_with_group.xml
Loading errors out with: 
`Loading configuration file with schema version 4.40
Error: Failed to convert EventFiltering nodes: simple_with_group.xml`

I noticed that this is because the "wrong" numerical order of the tag IDs. 
DriverLoad 6
ProcessTerminate 5
NetworkConnect 3

So I changed the order to be numerical "correct" for the IDs 3,5,6 and named the file simple_with_group_right_order.xml
Loading error out with:
`Loading configuration file with schema version 4.40
RuleEngine Error: Multiple rule filters of the same type - Last error: The data is invalid.`
I noticed that this error occurs a soon as there are 2+ tags in a group.

Even the very simple config below errors out:
`<Sysmon schemaversion="4.40">
	<EventFiltering>
    <RuleGroup name="group 1" groupRelation="and">
		<ProcessCreate onmatch="include">
			<Image condition="contains">timeout.exe</Image>
		</ProcessCreate>
		<NetworkConnect onmatch="include">
		  <DestinationPort>80</DestinationPort>
		</NetworkConnect>		
    </RuleGroup>
  </EventFiltering>
</Sysmon>`

[12.03.zip](https://github.com/MicrosoftDocs/sysinternals/files/5672965/12.03.zip)

Pls proof me wrong, but I think the issues from #282,#283 are even worse now.

**Comment by super0xbad1dea** [comment]
Event in Sysmon 13.00 this issue still exists :/

**Comment by super0xbad1dea** [comment]
@analyze-v Can you take a look at this plz. Thanks

**Comment by foxmsft** [comment]
We still don't support multiple events under the same `RuleGroup`, I think the docs page needs some more explanations on this and I'll take care of this.

The recommended way to get this

```xml
<Sysmon schemaversion="4.50">
    <EventFiltering>
        <RuleGroup name="group 1" groupRelation="and">
            <ProcessCreate onmatch="include">
                <Image condition="contains">timeout.exe</Image>
            </ProcessCreate>
            <NetworkConnect onmatch="include">
                <DestinationPort>80</DestinationPort>
                <DestinationPort>443</DestinationPort>
            </NetworkConnect>
        </RuleGroup>
    </EventFiltering>
</Sysmon>
```

is 

```xml
<Sysmon schemaversion="4.50">
    <EventFiltering>
        <RuleGroup name="group 1" groupRelation="and">
            <ProcessCreate onmatch="include">
                <Image condition="contains">timeout.exe</Image>
            </ProcessCreate>
        </RuleGroup>
        <RuleGroup name="group 2" groupRelation="and">
            <NetworkConnect onmatch="include">
                <DestinationPort>80</DestinationPort>
                <DestinationPort>443</DestinationPort>
            </NetworkConnect>
        </RuleGroup>
    </EventFiltering>
</Sysmon>
```

This is a peculiar use of XML, `RuleGroup` was introduced just to help switch between `or` and `and` for the specific nouns (such as `DestinationPort` under `NetworkConnect`) specified under a Sysmon event type.

**Comment by oppiman** [comment]
Thank you. I figured. But still figured, but still found it odd. 
What about the need to use the tags in the right numerical order of the ID?
I mean, ok, it is easy to circumvent that, but shouldn't xml not care about ordering?

**Comment by super0xbad1dea** [comment]
@foxmsft I'm sorry, but I can show you that this problem is not only because of Rule groups or order of Event IDs

Case 1: Sysmon 13.00 with working mini config - 2 Rule Groups
```xml
<Sysmon schemaversion="4.50">
	<DnsLookup>False</DnsLookup>
	<HashAlgorithms>*</HashAlgorithms>
	<EventFiltering>
		<RuleGroup name="group1" groupRelation="or">
			<ProcessCreate onmatch="exclude"/>
		</RuleGroup>
		<RuleGroup name="group2" groupRelation="or">
			<FileCreateTime onmatch="include"/>
		</RuleGroup>
	</EventFiltering>
</Sysmon>
```

Output:
```
C:\Users\engineer\Desktop\sysmon\1300>Sysmon64.exe -i ..\working_with_2_rulegroups.xml -t


System Monitor v13.00 - System activity monitor
Copyright (C) 2014-2021 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.50
Configuration file validated.
SysmonDrv installed.
[R] No global rule or pre-filtered for 16
Event SYSMON_SERVICE_CONFIGURATION_CHANGE
        UtcTime: 2021-01-12 21:15:45.385
        Configuration: C:\Users\engineer\Desktop\sysmon\working_with_2_rulegroups.xml
        ConfigurationFileHash: SHA256=6CDC8F420C7765C4A44665396828B1145CD631CD82914809581001857E1EB625
Starting SysmonDrv.
SysmonDrv started.
```

Case 2: Sysmon 13.00 with not working mini config - 1 Rule Group
```xml
<Sysmon schemaversion="4.50">
	<DnsLookup>False</DnsLookup>
	<HashAlgorithms>*</HashAlgorithms>
	<EventFiltering>
		<RuleGroup name="group1" groupRelation="or">
			<ProcessCreate onmatch="exclude"/>
			<FileCreateTime onmatch="include"/>
			<FileCreateTime onmatch="exclude"/>
		</RuleGroup>
	</EventFiltering>
</Sysmon>
```

Output:
```
C:\Users\engineer\Desktop\sysmon\1300>Sysmon64.exe -i ..\bug_with_1_rulegroup.xml -t


System Monitor v13.00 - System activity monitor
Copyright (C) 2014-2021 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.50
RuleEngine Error: Multiple rule filters of the same type - Last error: The data is invalid.

Error: Failed to correctly compute rule binary format
```

Case 3: Sysmon 13.00 with not working mini config - 2 Rule Groups
```xml
<Sysmon schemaversion="4.50">
	<DnsLookup>False</DnsLookup>
	<HashAlgorithms>*</HashAlgorithms>
	<EventFiltering>
		<RuleGroup name="group1" groupRelation="or">
			<ProcessCreate onmatch="exclude"/>
		</RuleGroup>
		<RuleGroup name="group2" groupRelation="or">
			<FileCreateTime onmatch="include"/>
			<FileCreateTime onmatch="exclude"/>
		</RuleGroup>
	</EventFiltering>
</Sysmon>
```

Output:
```
C:\Users\engineer\Desktop\sysmon\1300>Sysmon64.exe -i ..\bug_with_2_rulegroup.xml -t


System Monitor v13.00 - System activity monitor
Copyright (C) 2014-2021 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.50
RuleEngine Error: Multiple rule filters of the same type - Last error: The data is invalid.

Error: Failed to correctly compute rule binary format
```

I've uninstalled before every try. Each of the above 3 config files work with Sysmon 12.01.

**Comment by super0xbad1dea** [comment]
I did a further check, because I thought that a config just with 
```xml
<FileCreateTime onmatch="include"/>
<FileCreateTime onmatch="exclude"/>
```
could be an issue, but I have the same behaviour when I extend the config to
```xml
			<FileCreateTime onmatch="include">
				<Image condition="begin with">C:\Users</Image> <!--Look for timestomping in user area-->
			</FileCreateTime>
			<FileCreateTime onmatch="exclude">
				<Image condition="image">OneDrive.exe</Image> <!--OneDrive constantly changes file times-->
				<Image condition="contains">setup</Image> <!--Ignore setups-->
			</FileCreateTime>
		</RuleGroup>
```

**Comment by super0xbad1dea** [comment]
Hey guys,

I got it now, and understand what you've been explaining @foxmsft 

So, you need a rule group around each EID include/exclude.
```xml
<Sysmon schemaversion="4.50">
	<DnsLookup>False</DnsLookup>
	<HashAlgorithms>*</HashAlgorithms>
	<EventFiltering>
		<RuleGroup name="" groupRelation="or">
			<ProcessCreate onmatch="exclude">
				<Rule groupRelation="and">
					<Image condition="end with">AcroRd32.exe</Image>
					<CommandLine condition="contains any">/CR;channel=</CommandLine>
				</Rule>
			</ProcessCreate>
		</RuleGroup>
		<RuleGroup name="" groupRelation="or">
			<FileCreateTime onmatch="include">
				<Image condition="begin with">C:\Users</Image>
			</FileCreateTime>
		</RuleGroup>
		<RuleGroup name="" groupRelation="or">
			<FileCreateTime onmatch="exclude">
				<Image condition="contains">setup</Image>
			</FileCreateTime>
		</RuleGroup>
	</EventFiltering>
</Sysmon>
```

But this behaviour is since version 12.03. Anyway, that's the solution for me

**Comment by foxmsft** [comment]
This will most probably be covered and made to act consistently in a future release. Closing the issue for now, thanks a lot for reporting!
