### ISSUE TITLE
Process Explorer: crashes when decoding handle's access mask

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#333]
Crashes when decoding handle's (Process and Thread) access mask 0x1F3FFF.
To reproduce the bug, open handles view of Windows PowerShell (not Core).

**Comment by foxmsft** [comment]
Do you have any Unicode characters in any of the handles? Do you manage to have a glimpse at the view (works here)?

**Comment by AndreyBazhan** [comment]
![Capture](https://user-images.githubusercontent.com/12948835/102609309-eb321e80-4133-11eb-9861-a4485257c3be.PNG)

**Comment by foxmsft** [comment]
I managed to repro! Thanks for the report!
