### ISSUE TITLE
Process Explorer: leaks memory when opening handle's properties->security->advanced dialog

### ISSUE THREAD

**Issue by AndreyBazhan** [MicrosoftDocs/sysinternals#334]
Leaks memory when opening handle's properties->security->advanced dialog.
Sometimes it's 100-200 MB and sometimes 1-3 GB.

**Comment by foxmsft** [comment]
Thanks for the report, going to provide a fix in an upcoming release.

**Comment by AndreyBazhan** [comment]
Thank you.
