### ISSUE TITLE
error getting the evt dll (wevtapi.dll): 87  install sysmon in window2008R2 SP1 

### ISSUE THREAD

**Issue by zusini** [MicrosoftDocs/sysinternals#335]
System Monitor v12.03 - System activity monitor
Copyright (C) 2014-2020 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com

error getting the evt dll (wevtapi.dll): 87
Sysmon64 installed.
SysmonDrv installed.
StartService failed for SysmonDrv:
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
Failed to start the driver:
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

- i use packet sysmon for win7, window server 2008 late . 

Thank.

**Comment by foxmsft** [comment]
Windows 8.1 is the oldest supported version. Refer to the [Windows lifecycle page](https://docs.microsoft.com/en-us/lifecycle/faq/windows) to see what's the current supported status. Did you manage to see this on a more recent version of the OS?

**Comment by foxmsft** [comment]
Hi @zusini. I have managed to successfully install the latest Sysmon, v13.02, on both Vista and 2008R2. Did you recently try again with the latest official release?

**Comment by foxmsft** [comment]
Closing this as I expect this behavior to have been improved in recent versions.
