### ISSUE TITLE
BG Info 4.22 not working with scripts

### ISSUE THREAD

**Issue by weellio** [MicrosoftDocs/sysinternals#34]
BG info crashes when running vbs scripts.
here  is a simple script for ip info in a format that allows multiple nics. 
Thit crashes the latest version

``
strMsg = ""
strComputer = "."

Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\" & strComputer & "\root\cimv2")
Set IPConfigSet = objWMIService.ExecQuery("Select IPAddress, description from Win32_NetworkAdapterConfiguration WHERE IPEnabled = 'True'")

For Each IPConfig in IPConfigSet

 If Not IsNull(IPConfig.IPAddress) Then
 For i = LBound(IPConfig.IPAddress) To UBound(IPConfig.IPAddress)
	If Not Instr(IPConfig.IPAddress(i), ":") > 0 Then
		If UBound(IPConfig.IPAddress) = 1 then	
  			strMsg = strMsg & "                                                (" & IPConfig.IPAddress(0) & ") & (" & IPConfig.IPAddress(1) & ")" & vbCrLf
  		Else
  			strMsg = strMsg & "                                                (" & IPConfig.IPAddress(0) & ") & (Disabled)" & vbCrLf
  		End If
  		Exit For
	ElseIf Not Instr(IPConfig.IPAddress(i), ".") > 0 Then
		If UBound(IPConfig.IPAddress) = 1 then	
  			strMsg = strMsg & "                                                (" & IPConfig.IPAddress(0) & ") & (" & IPConfig.IPAddress(1) & ")" & vbCrLf
  		Else
  			strMsg = strMsg & "                                                (Disabled) & (" & IPConfig.IPAddress(0) & ")" & vbCrLf
  		End If
		Exit For
	End If
 Next
 End If
Next
If Right(strmsg,2) = vbCrLf Then 
	strmsg = Left(strmsg,Len(strmsg)-2)
End If

if len(strMsg) = 0 Then 
	strMsg = "                                                (No IpAddresses)"
End if

Echo strMsg
``

**Comment by weellio** [comment]
4.25 still appears to have this same issue.

**Comment by lukekim** [comment]
Hi, thanks for reporting this. The issue should have been fixed in 4.26, please let us know if it is still not working for you.
