### ISSUE TITLE
is there a sc ??

### ISSUE THREAD

**Issue by alexa872** [MicrosoftDocs/sysinternals#344]
hii for anyone reading this, is there a source code for these tools ... i want the source code of "listdlls" , i downloaded it as a executable but i really want the code, if it is not available i want something that at least enumerate processes called

**Comment by zodiacon** [comment]
The code is not public, but you can use the functions CreateToolhelp32Snapshot, Process32First/Next to enumerate processes and also DLLs with Module32First/Next

**Comment by alexa872** [comment]
> The code is not public, but you can use the functions CreateToolhelp32Snapshot, Process32First/Next to enumerate processes and also DLLs with Module32First/Next

thank you for the advice, but is there a way to know the api functions loaded to the memory from a specific process or from User32.dll or Kernel32.dll for example, it is like api hooking but i just want to know the function's name  i dont want to place a code or jump instruction or what ever, thank you again !

**Comment by zodiacon** [comment]
The simplest thing you can do with any executable is look at it in some PE viewer to see its imports, showing the DLLs and functions imported from them, The dumpbin VS tool can do that for you (and there are a few graphical tools for that as well)
