### ISSUE TITLE
TCPview hide known connections

### ISSUE THREAD

**Issue by sjsoliveira** [MicrosoftDocs/sysinternals#345]
Hi,
as an idea, I think it would be important to allow user to hide connections one consider as "known ones". Therefor allowing us to hide such kind of connections from the active listing. So that we could keep the screen clear, at one point, just showing the new, not usual ("known"), connections.
Thank you.

**Comment by zodiacon** [comment]
The next version of TcpView will support quick search that would allow hiding uninteresting endpoints
