### ISSUE TITLE
Procmon 3.61 not working in Win7 dev VM - Unable to load Process Monitor Device Driver

### ISSUE THREAD

**Issue by wesinator** [MicrosoftDocs/sysinternals#349]
Sorry if this is wrong place to report issues, it's just easier to report in GH and seems like tool bugs reported here before have been addressed.

**To reproduce:**
IE 8 Win7 VM (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) in Virtualbox

Procmon 3.61.0.0 (latest)

Download and run (I had to download Firefox from ftp.mozilla.org to even have a working browser to download procmon, you can try testing on IE11 VM for modern browser). 

`Unable to load Process Monitor Device Driver` 

![image](https://user-images.githubusercontent.com/5124946/108162055-4e035000-70ba-11eb-8c17-ac735aab8afb.png)

Thanks,

**Comment by foxmsft** [comment]
Windows 7 is not supported anymore - check [with Windows](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet). I'll have a look here, but no promises.

**Comment by wesinator** [comment]
> Windows 7 is not supported anymore - check [with Windows](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet). I'll have a look here, but no promises.

@foxmsft I don't think that is the reason why process monitor does not run, unless it has to do with driver signing expiration. 

If that is the case and it is actually no longer supported, then these docs should be updated because they currently say `Windows Vista and higher` 
https://github.com/MicrosoftDocs/sysinternals/blob/master/sysinternals/downloads/procmon.md#download 

But again I don't think that is the issue here 

Please reopen this issue. 

Thanks,

**Comment by foxmsft** [comment]
Hi @wesinator, tracking this one internally and I'll try to solve it for the next ProcMon release, in the next couple of months.

**Comment by mencall** [comment]
Around some point, Microsoft enabled a dual-signature policy (i.e., the program adds both sha1 and sha256 digital signatures for staging).
Then, as of Process Monitor 3.53, Microsoft removed the sha1 signature (only the sha256 signature was retained).
The default unanswered Win7 does not support sha2 signatures, so Process Monitor prompts for an error that does not load the driver (embedded driver file: procmon .sys).
So there are two workarounds (Win7):
a. Use of lower versions such as 3.52;
b. Update patches (KB3033929);
------------------------------
大概从某个时间开始，微软启用了双签名策略（即程序同时添加sha1和sha256数字签名，过渡用）。
然后，自 Process Monitor 3.53 起，微软删除了sha1签名（只保留sha256签名）。
而默认的未更新补丁的Win7并不支持sha2签名，所以Process Monitor会提示无法加载驱动（嵌入的驱动文件：procmon.sys）的错误。
所以有两种解决方法（Win7）：
a.使用低版本如3.52；
b.更新补丁（KB3033929）；
-
ps，防火墙实在太讨厌了，传个图片文件累死。

![Process Monitor版本差别1](https://user-images.githubusercontent.com/9344680/130041794-7b19b7a9-50cc-4812-a73f-b55ffc120cd2.png)
![Process Monitor版本差别2](https://user-images.githubusercontent.com/9344680/130042372-215e5df0-f245-4578-a629-4463261c18ca.png)
![Process Monitor版本差别3](https://user-images.githubusercontent.com/9344680/130044450-15ba691a-c6ef-47d8-8fd1-6b33cd5493ec.png)

**Comment by ariccio** [comment]
You know, it would be nice if Procmon bothered to bubble the actual error up to the user! Telling me it can't load the device driver is pretty useless.

**Comment by wesinator** [comment]
> You know, it would be nice if Procmon bothered to bubble the actual error up to the user! Telling me it can't load the device driver is pretty useless.

@ariccio it's a missing system feature update. the program doesn't know this.

you need to install these:
https://docs.microsoft.com/en-us/security-updates/SecurityAdvisories/2015/3033929?redirectedfrom=MSDN
https://support.microsoft.com/en-us/topic/sha-2-code-signing-support-update-for-windows-server-2008-r2-windows-7-and-windows-server-2008-september-23-2019-84a8aad5-d8d9-2d5c-6d78-34f9aa5f8339 

Hope this helps,

**Comment by al20878** [comment]
JFYI, procmon is broken again with the same popup on Win7...   (And the mentioned patches for signing do not help.)  Yeah, yeah, I know that it's not supported...

**Comment by AR0x7E7** [comment]
can confirm, the patch is already installed, still getting the error message

**Comment by meir555** [comment]
The latest version of procmon that works for me on Windows 7 x64 SP1 is v3.86.
You must install KB4474419 and KB4490628.

For downloading the KB update use: https://www.catalog.update.microsoft.com/

For more info about the SHA2 updates: https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

**Comment by foxmsft** [comment]
We're in fact using the driver kit for Windows 8, so I would be surprised if it worked with 7 at all.

**Comment by meir555** [comment]
> We're in fact using the driver kit for Windows 8, so I would be surprised if it worked with 7 at all.

Actually, on Windows 7 SP1 _**x86**_, even the current version of procmon (v3.93) works fine.

**Comment by RadarNyan** [comment]
As the time of writing this comment, the latest version of Procmon (3.95.0.0) works on Windows 7 SP1 64-bit with the following patches installed:

Kernel-Mode Driver Framework v1.11 (KB2685811)
User-Mode Driver Framework v1.11 (KB2685813)
Security Update for Microsoft Windows (KB4474419)
Update for Microsoft Windows (KB4490628)

The last one (KB4490628) is **NOT** optional. Without it, Windows 7 is able verify SHA-2 certificates (with KB4474419 installed) but Procmon wouldn't run. I originally skipped it since it's titled "Servicing Stack Update for Windows 7 for x64-based Systems" and I wasn't planning to use Windows Update, however Procmon wouldn't run without it installed (not sure why though, other applications I use which uses SHA-2 drivers like npcap runs just fine)

**Comment by BFNOC** [comment]
After installing KB4474419 and KB4490628 on my Windows 7, I still received the "Unable to load Process Monitor Device Driver" error. However, after running procmon 3.86 once, the subsequent version, procmon 3.91, was able to run without issues. I'm not sure if this information is helpful for you.

**Comment by Copper-Field** [comment]
> After installing KB4474419 and KB4490628 on my Windows 7, I still received the "Unable to load Process Monitor Device Driver" error. However, after running procmon 3.86 once, the subsequent version, procmon 3.91, was able to run without issues. I'm not sure if this information is helpful for you.

I second this: 3.96-4.01 didn't load on Win7x64 till I have got [v.3.84](https://web.archive.org/web/20210820090300if_/https://download.sysinternals.com/files/ProcessMonitor.zip) and run it. After that v.4.01 started to load and work normally.
