### ISSUE TITLE
Procmon for ARM64 adds "Procmon.exe" instead of "Procmon64a.exe" to the default filters

### ISSUE THREAD

**Issue by davidebeatrici** [MicrosoftDocs/sysinternals#361]
![](https://user-images.githubusercontent.com/5897523/112111380-66ccbd00-8bb4-11eb-89ee-48ed61c3e6f8.png)

Also, `procexp.exe` should be `procexp64a.exe`.

**Comment by zodiacon** [comment]
Thanks for reporting this, we'll add a bug to our backlog.

**Comment by davidebeatrici** [comment]
You're welcome.
