### ISSUE TITLE
Duplicate tcpview.exe in the zip file

### ISSUE THREAD

**Issue by MarcoPeraza** [MicrosoftDocs/sysinternals#371]
The latest zip file available as the first link on this page https://docs.microsoft.com/en-us/sysinternals/downloads/ (https://download.sysinternals.com/files/SysinternalsSuite.zip) has two versions of TcpView.exe. One has an upper case first letter and one does not. I'm pretty sure this is an oversight and don't know where else to report it. It causes errors when unpacking the zip and risks that users will use the wrong version.

**Comment by zodiacon** [comment]
Thank you for reporting this!

**Comment by foxmsft** [comment]
Should be resolved with the latest release.
