### ISSUE TITLE
Disk2VHD select devices without drive letter

### ISSUE THREAD

**Issue by nona00** [MicrosoftDocs/sysinternals#381]
I want to backup several partitions by using the command line arguments of disk2vhd.

I'm not able to pass a parameter to select for example the hidden recovery partitions.

In addition the partition sorting shown in disk2vhd does not match the physical layout.

**Comment by nona00** [comment]
[https://www.directupload.net/file/d/6177/cd52xzs2_png.htm](url)

**Comment by nicholaspct** [comment]
Hello, I am also interested in backing up several partitions using the command line.  Did you find a solution yet? Thanks

**Comment by nona00** [comment]
Backing up several partitions which do have drive labels works by using e.g.:
disk2vhd C: D: <vhdfile>

But this does not work for partitions \\?Volume{...}\ without labels.

**Comment by nona00** [comment]
Any news on this issue. v2.02 does not contain a fix?

**Comment by cap4cho** [comment]
News about this?

**Comment by sronline** [comment]
@foxmsft: any news on this?
