### ISSUE TITLE
Syntax is not interpreted correctly, potential data loss. 

### ISSUE THREAD

**Issue by harangutang** [MicrosoftDocs/sysinternals#383]
I can confirm that this issue, which I have seen in several "closed" issues, is not caused only by user entering incorrect syntax. 

I entered  `sdelete64.exe -p 2 -c 2 C:`  into both usermode and elevated cmd.exe and powershell.exe, and was given this exact output each time. Also I tried each variation with sdelete.exe 

**SDelete is set for 2 passes.

Cleaning disk 2:

Error opening disk 2:
The system cannot find the file specified.

Cleaning disk C::

Error opening disk C::
The system cannot find the file specified.**

`sdelete64.exe -p 2 -c 2 C`  outputs 

**SDelete is set for 2 passes.

Cleaning disk 2:

Error opening disk 2:
The system cannot find the file specified.

Cleaning disk C:

Error opening disk C:
The system cannot find the file specified.**

I also tried `sdelete64.exe -c2 C`   and `sdelete64.exe -p2 -c2 C`  and `sdelete64.exe -p 2 -c2 C`  All of which result in the same pattern of errors.

The only way to get sdelete to recognize the drive and actually execute is by skipping the %free argument, like so: `sdelete64.exe -c C:`

Luckily it's so borked that it isn't actually managing to do what it says it wants to do, which is totally wipe my disk #2. Even if that is a misinterpretation on my part, there's no way that it's supposed to be unable to find C: when the percent free argument is included.

**Comment by harangutang** [comment]
Also the command that works, `sdelete64.exe -c C:` will sometimes output 

*SDelete is set for 1 pass.
**Cleaning** free space on C:\: 6%*

Which is what I would expect. However other times, even if I run the exact same command again on the same instance of the console, it will sometimes output:


*SDelete is set for 1 pass.
**Zeroing** free space on C:\: 0%* 


So, maybe some kind of weird race condition going on there or something..

**Comment by foxmsft** [comment]
This should work fine with [v2.05](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete).
