### ISSUE TITLE
Sysmon: Update documents for schema version 4.70 which has Event ID 26

### ISSUE THREAD

**Issue by Richman711** [MicrosoftDocs/sysinternals#396]
Upon reviewing the latest version of sysmon (13.21.0.0) I have identified that the schema has been updated to 4.70, including Event ID 26. Event ID 26 has not been identified within the official documents for sysmon. Since Event ID 26 is similar to Event ID 23, the addition to the documentation should be simple as the only difference is that Event ID 26 does not archive a copy of the file deleted. 

I would also like to request that a mention be added to Event 23 that explains that a copy of the deleted file is saved to the root directory. In the case of the OS drive C:\Sysmon and if not careful can fill all available space with copies of the deleted file.

**Comment by foxmsft** [comment]
Oops, thanks for pointing this out, the update will roll out soon!
