### ISSUE TITLE
Is there a way to identify the files locked by a different process in a linux container?

### ISSUE THREAD

**Issue by ram62836** [MicrosoftDocs/sysinternals#416]
Im trying to find a way to identify the the process locking the files, by which the read process is getting failed with IOException. Online source suggested Handle.exe, not sure it if works in a linux container. Is there a way to do this via code?

**Comment by foxmsft** [comment]
Hey, a way I could think of would be searching in Process Explorer (Ctrl+Shift+F) for the locked file name. You might find the win32 processs with handles to the file.

Closing this, as it's not docs (Sysinternals) specific.

**Comment by ram62836** [comment]
I'm using CIFS to mount the network directory. It is kind of transient, after resetting the connection it is working as normal.
