### ISSUE TITLE
Switch to preserve dead processes in view

### ISSUE THREAD

**Issue by gxtaillon** [MicrosoftDocs/sysinternals#417]
Hi, 

Is there a switch to keep dead processes properties in view?

I'd like to see what the virustotal results are for short lived processes and I can't click fast enough to get them.

Best!

**Comment by zodiacon** [comment]
There is no such switch. You can press SPACE to freeze the display. You can also change the highlight duration to 9 seconds, which should give you enough time to see the results,
Regardless, if you know where the file is on disk, just submit it yourself.

**Comment by gxtaillon** [comment]
That didnt work but I found out about Sysmon, and I managed to get an hash from there.

Thank you
