### ISSUE TITLE
BGInfo and BGInfo64 v4.23 crash when adding/using certain custom fields

### ISSUE THREAD

**Issue by radreck** [MicrosoftDocs/sysinternals#44]
When adding a custom field that utilizes certain options, the program crashes after clicking the final OK button.

File contents: crashes
WMI query: crashes

Sample WMI query used:  SELECT CurrentClockSpeed FROM Win32_Processor WHERE DeviceID='CPU0'

Additionally, it is unable to open any .BGI saved that utilizes any custom fields. Curiously, attempting to open said .BGI files does not cause a crash, it just reverts back to the main screen.

Event Log: Event ID 1000
Faulting application name: BGInfo64.exe, version: 4.23.0.0, time stamp: 0x5a2c885b
Faulting module name: BGInfo64.exe, version: 4.23.0.0, time stamp: 0x5a2c885b
Exception code: 0xc0000409
Fault offset: 0x000000000025119c
Faulting process id: 0x8e8
Faulting application start time: 0x01d373b92b0d50d6
Faulting application path: C:\UTILS\BGInfo\BGInfo64.exe
Faulting module path: C:\UTILS\BGInfo\BGInfo64.exe
Report Id: c2aa43d5-9106-4ac2-ab0e-ef836581b402
Faulting package full name: 
Faulting package-relative application ID: 

Event Log: Event ID 1001
Fault bucket 1809349670476882291, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: BGInfo64.exe
P2: 4.23.0.0
P3: 5a2c885b
P4: BGInfo64.exe
P5: 4.23.0.0
P6: 5a2c885b
P7: 000000000025119c
P8: c0000409
P9: 0000000000000008
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER474E.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_BGInfo64.exe_fc378249c91358d2c47ae6bd5e66bf6f2622b9_aeba361a_03ac81c7

Analysis symbol: 
Rechecking for solution: 0
Report Id: c2aa43d5-9106-4ac2-ab0e-ef836581b402
Report Status: 0

**Comment by lukekim** [comment]
Hi, thanks for reporting this issue. It should be fixed in 4.26, please let us know if it is not.
