### ISSUE TITLE
Sysmon v13.24 CopyOnDeletePE feature

### ISSUE THREAD

**Issue by heck-gd** [MicrosoftDocs/sysinternals#440]
I get the following output when attempting to load a config that has `<CopyOnDeletePE>True</CopyOnDeletePE>` under its `Sysmon` top-level element. Both, the documentation and command-line help describe this as a valid option.

```
Loading configuration file with schema version 4.70
Element Sysmon content does not follow the DTD, expecting (EventFiltering | ArchiveDirectory | CaptureClipboard | Driver
Name | PipeMonitoringConfig | HashAlgorithms | DnsLookup | ProcessAccessConfig | CheckRevocation)*, got (HashAlgorithms
CheckRevocation DnsLookup ArchiveDirectory CopyOnDeletePE EventFiltering )
No declaration for element CopyOnDeletePE
LIBXML2 Error: Failed to validate the xml configuration: .\config.xml
```

When searching in the binary, I find references to `CopyOnDelete_PE` (and same for the other CopyOnDelete* tags), so perhaps there is some naming inconsistency there? With underscore the config also isn't accepted, though.

**Comment by foxmsft** [comment]
I see this flag as disabled in the current builds - I think there's still some work open for it. Just avoid for the time being and keep an eye on future releases, I'll mention in the changes section after I enable it again.

Thanks!
