### ISSUE TITLE
BGInfo /TIMER:0 doesn't work, creates zombie process.

### ISSUE THREAD

**Issue by billfrench** [MicrosoftDocs/sysinternals#46]
On the Dec 12th version, on Server 2016, if I run "bginfo.exe /timer:0" -- nothing seems to happen.  I see there is a bginfo process running in taskmanager.  And, if I press "c" the "user defined fields" pops up, so it's like interface is running invisibly.  Consequently, this version doesn't work through GPO and such, and fills systems with zombie copies of bgingo processes.  It does the same thing with bginfo and bginfo64.

**Comment by andrewvandyk** [comment]
Seeing the same issue on Windows 10 1709 x64. Using timer with any value other than 0 works.

**Comment by lukekim** [comment]
Thanks for reporting this, we are investigating.

**Comment by analyze-v** [comment]
Unable to reproduce this on the latest version. Looking through the revision history there were a lot of GUI changes between now and then so hopefully this has been resolved. If not please feel reach out to us again.
