### ISSUE TITLE
PSShutdown - Windows 11 Compatibility

### ISSUE THREAD

**Issue by wise-io** [MicrosoftDocs/sysinternals#485]
**PsShutdown** has some compatibility issues with **Windows 11**:

- The `-m "text"` parameter does not display a message to the interactive user
- The `-c` parameter does not allow the interactive user to abort the shutdown

To reproduce, run the following on a Windows 11 machine: `PsShutdown -r -c -m "test"`

**Comment by foxmsft** [comment]
Thanks for the report, will include this for one of the future releases!

**Comment by hobbes** [comment]
does not work on windows 10 either

**Comment by vseven** [comment]
From looking at other posts it seems it doesn't work on any 64 bit OS.  As a workaround I'm using this:

```
PsExec.exe \\ComputerName msg * Your computer will be rebooted for updates in 2 minutes.  Please save anything you have open.
PSShutdown.exe \\ComputerName -t 120 -e p:0:0

```
Would be nice for PSShutdown to do it on it's own but this works in a pinch.  You can also put it into a batch file and call a text file that has a list of computer names:

```
For /f "tokens=*" %%i in (ComputersToReboot.txt) DO (
     PSSHUTDOWN.exe -t 300 -r -f \\%%i >> ComputersToRebootResults.txt
     PsExec.exe \\%%i msg * Updates have been applied and your computer will reboot in 5 minutes.
)
```

**Comment by akaJuliaan** [comment]
Will this problem still be fixed?

**Comment by foxmsft** [comment]
This should work now with [version 2.6](https://learn.microsoft.com/sysinternals/downloads/psshutdown).

**Comment by NDCMCDN** [comment]
Not displaying -m in version 2.6.
