### ISSUE TITLE
Last version that runs on XP?

### ISSUE THREAD

**Issue by bushy555** [MicrosoftDocs/sysinternals#494]
All,

Am politely asking does anyone have any clues as to what the last version number is that actually runs successfully on x86 XP ?

thanks,

**Comment by foxmsft** [comment]
This should be quite a few years back. Which tool do you have in mind?

**Comment by xavery** [comment]
Latest SDelete at the time of writing (v2.04) works just okay on XP.

**Comment by foxmsft** [comment]
Closing - please do not run [out of support Windows versions.](https://learn.microsoft.com/en-us/lifecycle/faq/windows)
