### ISSUE TITLE
Suggestion: Improve navigation in ProcMon window

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/sysinternals#507]
Maybe add a ctrl+pg dwn/ctrl+pg up hotkey to instead of paging down/up one page to do an increment of 10. Often times I'm looking for the transition between multiple processes and while I could 'find' to the next one, I think having a 'large page up/down' option might be handy.

Just a thought anyway.

**Comment by foxmsft** [comment]
Thank you, coming up in a future point release!
