### ISSUE TITLE
ZoomIt [Request]: Stay in "type" mode when doing a left click :)

### ISSUE THREAD

**Issue by theelectricsoul** [MicrosoftDocs/sysinternals#525]
ZoomIt is fast. Pure love :). Here is a suggestion to make it faster 

# Scenario
User enters "type" mode and starts typing. Then the user wants to type somewhere else.

# Problem
There is no official function that allows the user to reposition the cursor without leaving the "type" mode.

# Workaround
Using the scroll wheel will **release the cursor** but ZoomIt will **stay in "type" mode**. 

# Suggestion
When in "type" mode

- left click will release cursor but stay in type mode
- right click will exit type mode

**Comment by foxmsft** [comment]
Type mode is intended as each block being a different "action" within ZoomIt. This new behavior would make things more complicated. Noted, but no promises!
