### ISSUE TITLE
psshutdown does not support Modern Standby

### ISSUE THREAD

**Issue by Noexpert** [MicrosoftDocs/sysinternals#540]
It puts the machine in a deeper state of sleep than S0 Modern Standby.
The only way I can wake the machine is by pressing the power button; mouse the keyboard do not work.

**Comment by foxmsft** [comment]
Last week's [version 2.6](https://learn.microsoft.com/sysinternals/downloads/psshutdown) should address this with the new `-x` flag. Give it a try!
