### ISSUE TITLE
Unable to load Process Monitor Device driver

### ISSUE THREAD

**Issue by smaillet** [MicrosoftDocs/sysinternals#552]
Using latest ZIP file downloaded from MS site every time I start procmon.exe it pops up a dialog that says:
"Unable to load Process Monitor Device driver"

ProcMon:
v3.90

OS:
Windows 10 21H2 - 19044.1826 (AMD64)

I am a member of the administrators group and I allow it to elevate at start. 
I've tried with procmon.exe as well as procmon64.exe but neither works.

**Comment by smaillet** [comment]
UPDATE: Same thing happens for the Windows store version of the install. This thing just isn't compatible with this OS build... How can I get an older version that works?

(Which I quickly uninstalled after testing because it's obnoxious without a folder to group all the apps, too many apps cluttering the app list :( )

**Comment by foxmsft** [comment]
v3.91 should fix this even on AMD64, any luck?

**Comment by foxmsft** [comment]
Closing this issue as I've seen no new reports after 3.91.

**Comment by AK-CH** [comment]
3.91 (Intel) on WIndows 11 does not work for me. 
"Unable to load Process Monitor Device driver"

**Comment by d0vgan** [comment]
Unfortunately, this is **not** fixed for Windows 11 even in Process Monitor 3.95.
What is even worse, when you exit Process Monitor (e.g. via File -> Exit), under Windows 11 it remains in the running processes. Which means that if you had initially started it without admin privileges (resulting in "Unable to load Process Monitor Device driver"), this process remained in the running processes and blocked any further instances of Process Monitor to load its device driver. Surely, until you realize there was a "zombie process" of Process Monitor and kill it manually.

**Comment by sandip-shah** [comment]
Unfortunately, still not fixed in 3.96.  Windows 11 on ARM, within Parallels on a Mac.

**Comment by petergluck** [comment]
> Unfortunately, still not fixed in 3.96. Windows 11 on ARM, within Parallels on a Mac.

Maybe it's obvious, but I first ran procmon64.exe and got this error.  Then I realized that my Mac M2 chip is an ARM processor.  When I ran procmon64a.exe, it launched correctly.
