### ISSUE TITLE
Process Monitor updated on 7/29 however the SysInternals website does not mention this.

### ISSUE THREAD

**Issue by kezcik** [MicrosoftDocs/sysinternals#557]
Process Monitor updated on 7/29 however SysInternals Suite download still says the last update was on 7/19

also
SysinternalsSuite.zip includes the new Process Monitor files but is missing Procmon64a.exe which is available in the seperate Process Monitor download
https://download.sysinternals.com/files/ProcessMonitor.zip

**Comment by kezcik** [comment]
Seems the release dates for Process Monitor, BGInfo and ZoomIt have now updated to 7/29 however the entire suite is still dated 7/19 even though it includes these newer versions of BGInfo and ZoomIt.

**Comment by foxmsft** [comment]
Thanks for pointing it out, resynced once August's release was live.
