### ISSUE TITLE
ZoomIt - easy to lose drawing

### ISSUE THREAD

**Issue by w64bit** [MicrosoftDocs/sysinternals#565]
If you start drawing mode and draw something, after you press Esc, the drawing mode is closing with no prompt and you lose what you draw.
I propose:
- to change the Escape key to Draw hotkey (the hotkey to be toggle)
- to add a dialog when exiting draw mode for asking to save the drawing
Thank you

**Comment by foxmsft** [comment]
This behavior is by design. There's the `Ctrl+S` shortcut for saving the current screen as PNG, but otherwise dialogs just make it a bit clunkier to use.
