### ISSUE TITLE
add note that contig64 is broken

### ISSUE THREAD

**Issue by sthalik** [MicrosoftDocs/sysinternals#57]
Please add a note on the `contig` sysinternals page that the 64-bit version `contig64` is broken. I was consistently receiving STATUS_ALREADY_COMMITTED. The problem is shared by others, as per Google.

This isn't a bugfix request. But a note not to use the 64-bit version would save others after me a lot of pain. I was for a long time convinced it can't be made to work. See background.

- - -

Background:

I'm using a 2TB partition for bulk data storage. Bundled Windows defrag utility hangs while analyzing it.

A third-party defrag program skips over two 100 GB files, being preallocated VM disks. The files had lots of small fragments and a great amount of fragments in total.

**Comment by analyze-v** [comment]
Thanks for reporting. I have added this to our backlog
