### ISSUE TITLE
RDCMan Error incompatible mstscax.dll

### ISSUE THREAD

**Issue by Computer-Tsu** [MicrosoftDocs/sysinternals#586]
Microsoft Windows [Version 10.0.19043.1826]
RDCMan.exe version 2.90.1420.0 (2022-01-27)
mstscax.dll version 10.0.19041.1826 (2022-09-13)

RDCMan encountered an error during initialization. There are two likely causes for this: an incompatible version of mstscax.dll is registered or it is not registered at all. Please see the help file for details.

**Comment by foxmsft** [comment]
Does running

```cmd
regsvr32.exe C:\Windows\System32\mstscax.dll
```

from an elevated prompt change the outcome for RDCMan in any way?

**Comment by Ksaeger** [comment]
I'm having the same issue, but the suggestion to register the .dll did not resolve it.

Microsoft Windows version 10.0 19041.2075
mstscax.dll version 10.0.19041.2075
RDCMan.exe version 2.90.1420.0

**Comment by foxmsft** [comment]
Yes, this is what I suspect. Not calling [`SetDefaultdllDirectories(LOAD_LIBRARY_SEARCH_SYSTEM32)`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-setdefaultdlldirectories) basically allows RDCMan to work on such systems.

**Comment by Ksaeger** [comment]
Yes, I am going through Citrix Workspace v 19.12.5000.3(1912) to a virtual desktop I am trying to use RDCMan on. Thank you for working on a fix!

**Comment by Cosmo121** [comment]
Same issue here on the CU branch of Workspace and CVAD:
Win 10 21H2 build 19044.2364
CVAD 2209.0.0.52
RDCMan 2.90.1420

**Comment by Cosmo121** [comment]
Looks like this is fixed in 2.92. Thanks so much @foxmsft !

**Comment by cheesoon-sgp** [comment]
This new version 2.92 resolve my problem with the DLL incompatible error

**Comment by johnstep** [comment]
This was fixed in [RDCMan v2.92](https://techcommunity.microsoft.com/t5/sysinternals-blog/rdcman-v2-92-sysmon-v14-14-and-zoomit-v6-12/ba-p/3724973).

**Comment by gschrader** [comment]
@johnstep I still get the same error with 2.92

**Comment by johnstep** [comment]
Thanks. Can you confirm your Windows and mstscax.dll versions? We will investigate.

**Comment by gschrader** [comment]
@johnstep Windows 10 Enterprise 21H2, mstscax.dll (under \Windows\system32) version is 10.0.19041.2075

**Comment by RasmusDK** [comment]
Just want to add that I see the issue as @gschrader. Tested with RCDMan 2.93 today.
I am often using Citrix Workspace to connect to the machine on which I run RCDMan.

**Comment by gschrader** [comment]
I was given a new VDI and no longer have an issue, I’m not sure what would have changed.

**Comment by Computer-Tsu** [comment]
My affected Windows install was removed and I've not had an opportunity to recreate the issue or conditions. So, I would close the Issue until such time as it recurs.

The Citrix apps were very likely related as a common factor.
