### ISSUE TITLE
Sigcheck

### ISSUE THREAD

**Issue by optomux** [MicrosoftDocs/sysinternals#60]
Add lookup against Mozilla cert store.

Similar how RCC does it.
http://www.thewindowsclub.com/rcc-scan-windows-root-certificates-scanner

**Comment by lukekim** [comment]
Thanks for the suggestion!

**Comment by optomux** [comment]
It took you this long to view this? Wow.

**Comment by lukekim** [comment]
Yes, apologies. Sysinternals is still a best-effort supported project and we are doing our best. Thanks for the feedback, we've added this item to our backlog.
