### ISSUE TITLE
Sysmon 14.1 causing undoing changes loop for 24-48 hours on October 2022 KB's

### ISSUE THREAD

**Issue by stondino00** [MicrosoftDocs/sysinternals#604]
Since having 14.1 version of sysmon installed on Windows 10 and 11 workstations, any KB released this month will NOT install unless we disable the sysmon service or remove sysmon entirely.  Not sure where to properly file bugs for sysmon, so we are trying this here and see if it gets to Mark or not.  Thanks

**Comment by foxmsft** [comment]
Do you have any `FileBlockExecutable` rules in place?

**Comment by stondino00** [comment]
I'm using the most recent version of ion-storm's config.

https://github.com/ion-storm/sysmon-config

**Comment by foxmsft** [comment]
Try to get rid of the `FileBlockExecutable` rules and report back - I suspect there are some events about KBupdates being blocked from copying / creation.
