### ISSUE TITLE
Process explorer crash when view Strings on process with weird exe file.

### ISSUE THREAD

**Issue by AJ4real** [MicrosoftDocs/sysinternals#651]
If an executable has no strings, process explorer will freeze / crash when attempting to view the strings under properties for the specific process.

The executable used to discover this was the [Blackmagic Fairlight Sound Library](https://www.blackmagicdesign.com/support/download/05acbc36dbba4519a4972b7ddce31810/Windows) which can be found [here](https://www.blackmagicdesign.com/support/)

When the executable is opened as an archive, shows a folder named `Database` with a file `SoundLib.db` inside.

I also learned that when submitted to VirusTotal.com, returns "Unknown".
![Capture](https://user-images.githubusercontent.com/50052944/211671397-95980d00-7414-4ed9-bb03-a16b4e6b44bb.PNG)

**Comment by foxmsft** [comment]
Nice find, thanks for binging it up - I generally have access to this through Resolve.
