### ISSUE TITLE
Sysmon driver information missing

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/sysinternals#653]
https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon
https://github.com/MicrosoftDocs/sysinternals/blob/live/sysinternals/downloads/sysmon.md

The installation of a driver is mentioned.

What is the driver's file and name?

**Comment by foxmsft** [comment]
`sysmon -? config` will show the option to rename a driver - `DriverName`.

Will make the text more descriptive in a future release. Implicitly the driver is called `SysmonDrv.sys` and resides next to `sysmon[64].exe` in `C:\Windows`.
