### ISSUE TITLE
Procmon 3.92 cannot load filters.

### ISSUE THREAD

**Issue by cesaryuan** [MicrosoftDocs/sysinternals#655]
As mentioned in the title, `procmon` 3.92 cannot load filters on my computer but 3.61 is ok.

"cannot load filter" means there is no change to the filters when I load filters.

Here is the video: 

https://user-images.githubusercontent.com/35998162/212663977-95e1911c-8101-4564-b284-75ce25ef84c5.mp4

**Comment by johnstep** [comment]
This was fixed in [Process Monitor v3.93](https://techcommunity.microsoft.com/t5/sysinternals-blog/sysmon-1-1-for-linux-contig-v1-83-procdump-1-4-1-for-linux-and/ba-p/3764299).
