### ISSUE TITLE
Sigcheck lacks exit codes

### ISSUE THREAD

**Issue by dwaynebailey** [MicrosoftDocs/sysinternals#66]
It seems that sigcheck uses exit codes to communicate some issues with files.  E.g. 1 seems to indicate files that are unsigned (gleaned from the web).  I have an exit code of 4, but without docs I'm unable to know what that means.  Please add docs for exit codes to this and I'd assume other tools.

**Comment by dwaynebailey** [comment]
[Exit codes explained](https://books.google.co.uk/books?id=YQ86DQAAQBAJ&lpg=PT532&dq=sigcheck%20exit%20codes&pg=PT532#v=onepage&q=sigcheck%20exit%20codes&f=false)

Seems to be:
- -1 - bad file or option
- 0 - all signed or all unsigned filtered out
- +1 - number of unsigned or sigfnature failure files

**Comment by lukekim** [comment]
Thanks for reporting this, we've added the documentation item to our backlog.

**Comment by analyze-v** [comment]
When processing a folder this represents the number of unsigned files that were found.
