### ISSUE TITLE
RDCMan - No documentation on plugin functionality

### ISSUE THREAD

**Issue by Mojo-OG** [MicrosoftDocs/sysinternals#665]
As per these notes to the most recent [RDCMan version (v2.92)](https://techcommunity.microsoft.com/t5/sysinternals-blog/rdcman-v2-92-sysmon-v14-14-and-zoomit-v6-12/ba-p/3724973), RDCMan supposedly has plugin capabilities.

There is some speculative information online from community sources, but there is no official documentation or information on the capabilities for plugin development. Could we possibly get this added in the near future?

**Comment by foxmsft** [comment]
Good point, I overlooked describing `IPlugin`.
