### ISSUE TITLE
Feature request: Sysmon - add tag for revision number in config

### ISSUE THREAD

**Issue by glennbarrett** [MicrosoftDocs/sysinternals#666]
I believe it would be helpful to be able to add some kind of revision tag to the sysmon config, that is also logged into events. 

This would allow searching via SIEM (or equivalent) for only events that match a specific config revision.  

This would help with tuning and testing, as well as identifying hosts that are running non-current versions of the config.

**Comment by foxmsft** [comment]
Good point, considering it, thanks!
