### ISSUE TITLE
Calling sigcheck from console app returns exit code 1

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/sysinternals#677]
What means exit code 1?
`sigcheck` runs successfully, I get the expected results back, but the `sigcheck` subprocess returns `1` when I call it from my C# console application => `p.ExitCode == 1`.
No error data received through `ErrorDataReceived`.

What does it mean?

**Comment by foxmsft** [comment]
It means `un-signed.dll` and `signed.dll` aren't detected as signed. sigcheck has one path of returning 1 when the EULA check fails and then there's the signature verification path where it retuns the unsigned files count, all else is -1.
