### ISSUE TITLE
Disk Usage(DU) display issue on none-ASCII character

### ISSUE THREAD

**Issue by robertlzj** [MicrosoftDocs/sysinternals#689]
CHCP 963. When output (display) subdirectory using -l n，will get '?' on non-ASCII character?
![image](https://user-images.githubusercontent.com/7419030/230133798-e7484023-f5c3-4353-bfec-ec79989dcd9c.png)

also see [Windows Sysinternals on Q&A](https://learn.microsoft.com/en-us/answers/questions/722881/disk-usage-(du))

**Comment by NewcomerAl** [comment]
Hello.

Answered to your previous #519. Please take a look and try.
