### ISSUE TITLE
More dump types are needed to add for ProcDump v9.0

### ISSUE THREAD

**Issue by taehwalee** [MicrosoftDocs/sysinternals#69]
https://channel9.msdn.com/Shows/Defrag-Tools/Defrag-Tools-178-Sysinternals-ProcDump-v90

•-mc Write a 'Custom' dump file. Include memory defined by the specified MINIDUMP_TYPE mask (Hex). -md Write a 'Callback' dump file. Include memory defined by the MiniDumpWriteDump callback routine named MiniDumpCallbackRoutine of the specified DLL
•-mk Also write a 'Kernel' dump file. Includes the kernel stacks of the threads in the process. OS doesn't support a kernel dump (-mk) when using a clone (-r). When using multiple dump sizes, a kernel dump is taken for each dump size

**Comment by lukekim** [comment]
Thanks for the feedback, we've passed it onto the Defrag Tools crew.
