### ISSUE TITLE
Sysmon 14.15 failing to install on Server 2019/Win10-1809

### ISSUE THREAD

**Issue by robertriskin** [MicrosoftDocs/sysinternals#693]
Windows Server 2019 and Win10 1809 - Sysmon 14.14 was working perfectly and we just installed 14.15 on both operating systems and we get the following error:

"System Monitor v14.15 - System activity monitor
By Mark Russinovich and Thomas Garnier
Copyright (C) 2014-2023 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.20
Sysmon schema version: 4.83
Configuration file validated.
sysmon64 installed.
SysmonDrv installed.
StartService failed for SysmonDrv:
The specified procedure could not be found.
Failed to start the driver:
The specified procedure could not be found.

Stopping the service failed:
The service has not been started.
SysmonDrv removed.
Stopping the service failed:
The service has not been started.
sysmon64 removed."

Reverted to 14.14 which works fine. Not sure what the issue is here but can you please fix to install on Server 2019 and Win10 1809?

**Comment by foxmsft** [comment]
Yes, I can see the problem. Will come up with 14.16 shortly!

**Comment by foxmsft** [comment]
They said: "use undocumented syscalls". They said: "it will be fine" :D

**Comment by robertriskin** [comment]
So true! Really appreciate your super fast response :)

**Comment by foxmsft** [comment]
Should be fixed now, with [v14.16](https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon), thanks!
