### ISSUE TITLE
Issue in Pstools.chm

### ISSUE THREAD

**Issue by ylhyh** [MicrosoftDocs/sysinternals#70]
I have downloaded the PSTools package via the link "https://download.sysinternals.com/files/PSTools.zip", it seems there is a typo in the Pstools.chm file:

For "-e" option of PsExec, the description in Pstools.chm is "Loads the specified account's profile.", it should be "Does not load the specified account’s profile.", right?

**Comment by lukekim** [comment]
Thanks for reporting this, we are tracking this on our backlog.

**Comment by analyze-v** [comment]
Confirmed that this has been added to the backlog
