### ISSUE TITLE
SDelete -q option is undocumented

### ISSUE THREAD

**Issue by JustinWebDev** [MicrosoftDocs/sysinternals#704]
https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete
`sdelete [-p passes] [-r] [-s] [-q] <file or directory> [...]`
No description is given for _-q_ in the documentation page or the in-app help.

**Comment by foxmsft** [comment]
Thanks, solved it with [v2.05](https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete).
