### ISSUE TITLE
Mistakes in sysinternals/sysinternals/downloads/sysmon.md

### ISSUE THREAD

**Issue by uncletimmy3** [MicrosoftDocs/sysinternals#72]
Current sysmon.md does not match what is output by the command "sysmon.exe -? config".
Current sysmon.md:
_You can use both include and exclude rules for the same tag, where exclude rules override include rules. Within a rule, filter conditions on the same field have OR behavior, whereas conditions on different fields have AND behavior. In the sample configuration shown earlier, the networking filter uses both an include and exclude rule to capture activity to port 80 and 443 by all processes except those that have iexplore.exe in their name._

"sysmon.exe -? config":
_You can use both include and exclude rules for the same tag, where exclude rules override include rules.
Within a rule, filter conditions have OR behavior. In the sample configuration shown earlier, the networking filter uses both an include and exclude rule to capture activity to port 80 and 443 by all processes except those that have iexplore.exe in their name._

There is the same mistake above "Condition - Description"  table:
_Each filter can include zero or more rules. Each tag under the filter tag is a field name from the event. Rules that specify a condition for the same field name behave as OR conditions, and ones that specify different field name behave as AND conditions. Field rules can also use conditions to match a value. The conditions are as follows (all are case insensitive):_

**Comment by lukekim** [comment]
Thanks for reporting this, we are working on documentation updates.

**Comment by analyze-v** [comment]
This has been superseded by the introduction of rule groups.
