### ISSUE TITLE
Computers With Sysmon Version 15.0 Freezing in boot

### ISSUE THREAD

**Issue by AntonyNow19** [MicrosoftDocs/sysinternals#736]
Hello

Since we upgrade Sysmon to version 15.0 , we get some system freezing during the start on some computers.
First We install the sysmon with custom xml, so i tried to remove it, and install it with the default config. the problem still occur.
Only When we remove the Sysmon, or return to version 13 - it's solve the problem.

Is this issue already known?
Can you check the cause or fix it? Are there any windows log files to check?

Test Information
OS : Windows 10
Desktop model: DELL

Best Regards

**Comment by foxmsft** [comment]
Working on a fix for this one, to publish it later this October.

**Comment by AntonyNow19** [comment]
Hi,

Good to know. can you share some details about the resolving of this issue?

**Comment by or1165372** [comment]
Hi,

Any Update about the fix for this problem?

**Comment by foxmsft** [comment]
Would you like to try the new version before the publish? Drop me a message, it's this name, at hotmail.

**Comment by or1165372** [comment]
Hi,

I would like to check this version.
Can you update about the changes or if you have some idea about the reason
for this problem?

Best Regards.

**Comment by kronjob** [comment]
> Would you like to try the new version before the publish? Drop me a message, it's this name, at hotmail.

Hi @foxmsft 
We are also facing this issue with sysmon 15.
Kindly share this new version and we would like to check it out.
I have also dropped a message on your hotmail in this regard.

Thx.

**Comment by foxmsft** [comment]
Send me an email, @kronjob. It's my username, at hotmail.

**Comment by LiamSam2X** [comment]
Can you please share with us the fix or new version if any?  Thanks!

**Comment by foxmsft** [comment]
With v15.11 this shouldn't happen anymore. Please say if you're still experiencing issues.

**Comment by LiamSam2X** [comment]
Yes the issue has been fixed.  We've tested it after its released date.  Many thanks.
Sent from Yahoo Mail on Android 
 
  On Sun, 19 Nov 2023 at 2:57 pm, Alex ***@***.***> wrote:   


With v15.11 this shouldn't happen anymore. Please say if you're still experiencing issues.
