### ISSUE TITLE
slow deleting "large" (>100GB) files when sysmon is running

### ISSUE THREAD

**Issue by gixxerdaveneo** [MicrosoftDocs/sysinternals#757]
Example: when deleting a 110 GB file it takes 8 minutes with sysmon running. with sysmon not running file deletes in 1 second. 
The slow deletes started happening after upgrading sysmon from version 10.0.4.2 to 14.13.

**Comment by Zanglirex** [comment]
I've experienced this issue too. Through trial and error managed to track it down to the FileDeleteDetected Event (ID 26)

**Comment by foxmsft** [comment]
This is fixed in v15.11.

**Comment by gixxerdaveneo** [comment]
Will test v15.11 and report back

**Comment by foxmsft** [comment]
v15.12 is approaching, just test with v15.11 and make sure it's good for this case, will shortly publish the next one, as soon as Santa pleases.

**Comment by gixxerdaveneo** [comment]
> This is fixed in v15.11. If file deletion rules are selected and with file hashing enabled, at least the hashing operation will need to complete before the deletion is let through.

Is there a way to disable hash for only FileDeleteDetected Event (ID 26)

**Comment by foxmsft** [comment]
Not really, as the hash of the deleted object is the "identity" of the deletion being logged. But that's something definitely to consider!

**Comment by gixxerdaveneo** [comment]
Or disable hash when file size is over xGBs

**Comment by gixxerdaveneo** [comment]
We are using line 
<TargetFilename condition="excludes">C:\</TargetFilename> 
to exclude other drives/files from being monitored by sysmon.

Is there a better way? Exclude by file extension or file size?
