### ISSUE TITLE
sigcheck64.exe in batch problem

### ISSUE THREAD

**Issue by Blonder** [MicrosoftDocs/sysinternals#78]
Hello, I want to use the sigcheck64.exe in a batch file on a new clean OS to verify product version numbers. When used in the batch with the -nobanner option it always returned empty. After starting it one time manually and agreeing the EULA, it worked also in the batch.
Is there an option to pass the agreement as option to be able to use it in the batch witout starting it manually?
Thanks,
Andreas.

**Comment by analyze-v** [comment]
Bit late for the OP but for anybody else who comes across this, you can achieve this with most of the tools including sigcheck by using the -accepteula or /accepteula option
