### ISSUE TITLE
[BUG] Handle & Handle64 v5.0.0 incorrectly add "08X" to reported process handles # when using "... -u [name]" syntax

### ISSUE THREAD

**Issue by SwimmeRM** [MicrosoftDocs/sysinternals#792]
Today I've verified that Handle & Handle64 v5.0.0 incorrectly add "08X" to reported process handles # when using simpler "... -u [name]" syntax on command line. The same however doesn't happen if using simpler "... -p [pid]" syntax with same versions.
Previous version v4.22 didn't have the same issue, so pls see all evidences below: **1)** showing handle v5 and handle64 results; **2)** showing handle64 v5 with issue, while previous handle v4.22 doesn't have it; **3)** a smaller excerpt of handle64 v5 "... -p [pid]" also showing no issue.

**_P.S._** Because of the position where "...08X" unexpected additional characters are shown instead of where a more typical "...:" appears, chances are that issue might just depend by a simpler undetected typing error present in v5 code handling of output of "... -u [name]" syntax.
 
**1)**
02/04  9.54.28 C:\Windows\system32>"%SysWinInt%"\handle64 -u PDFforge

Nthandle v5.0 - Handle viewer
Copyright (C) 1997-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1dd3408X E:\Users\Alias1\Downloads\3rd_Pty\PDFforge.org
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1ea0c08X E:\Users\Alias1\Downloads\3rd_Pty\PDFforge.org

02/04  9.54.36 C:\Windows\system32>"%SysWinInt%"\handle -u PDFforge

Nthandle v5.0 - Handle viewer
Copyright (C) 1997-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1dd3408X E:\Users\Alias1\Downloads\3rd_Pty\PDFforge.org
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1ea0c08X E:\Users\Alias1\Downloads\3rd_Pty\PDFforge.org

**2)**
02/04 11.17.04 C:\Windows\system32>"%SysWinInt%"\handle64 -u PortableApps.com

Nthandle v5.0 - Handle viewer
Copyright (C) 1997-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           35a008X E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           ef6808X E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1cf7808X E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1dacc08X E:\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           26fcc08X E:\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           27f2808X E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com

02/04 11.21.24 C:\Windows\system32>"%SysWinInt%"\handle64 -u PortableApps.com

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           35A0: E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           EF68: E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1CF78: E:\Users\Alias1X\Downloads\3rd_Pty\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           1DACC: E:\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           26FCC: E:\PortableApps.com
explorer.exe       pid: 6116   type: File          CLNTNAME\Alias1           27F28: E:\Users\Alias1\Downloads\3rd_Pty\PortableApps.com

02/04 11.23.51 C:\Windows\system32>

**3)**

02/04 20.32.42 C:\Windows\system32>"%SysWinInt%"\handle64 -p 33444

Nthandle v5.0 - Handle viewer
Copyright (C) 1997-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

    C: File  (RW-)   C:\Windows\System32
   10: File  (RW-)   C:\Windows\winsxs\amd64_microsoft.windows.gdiplus_6595b6414
4ccf1df_1.1.7601.24498_none_145e59d68b8dcb8f
   C8: File  (---)   C:\Program Files\Microsoft Application Virtualization\Clien
t\Subsystems\AppVSentinel64.dll
   CC: File  (---)   C:\Program Files\Microsoft Application Virtualization\Clien
t\Subsystems\AppVEntSubsystems64.dll
  118: Section       \Sessions\1\BaseNamedObjects\windows_shell_global_counters
  194: File  (RW-)   C:\Windows\winsxs\amd64_microsoft.windows.common-controls_6
595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845
  19C: Section       \BaseNamedObjects\__ComCatalogCache__
  1AC: Section       \BaseNamedObjects\__ComCatalogCache__
  1B4: File  (R--)   C:\Windows\registration\R000000000008.clb
  1F0: File  (RW-)   C:\Windows\winsxs\amd64_microsoft.windows.common-controls_6
595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845
  224: File  (RW-)   C:\Windows\winsxs\amd64_microsoft.windows.common-controls_6
595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845
...

**Comment by foxmsft** [comment]
Found it, thanks for reporting!

**Comment by SwimmeRM** [comment]
:+1:
