### ISSUE TITLE
Sysmon64.exe -u removes logs from EventViewer

### ISSUE THREAD

**Issue by JiTmun** [MicrosoftDocs/sysinternals#797]
Hello,

When removing Sysmon v15.12. or 15.14 with Sysmon64.exe -u, logs doesn't appears anymore in the EventViewer.
It's like they are hidden because reinstalling sysmon makes them available again, also for logs before the uninstall time.

Where does the log go?

Error message for sysmon logs after uninstall 
![image](https://github.com/MicrosoftDocs/sysinternals/assets/95627331/5ef66183-87b9-4043-9354-8c54894b4ede)

Same as the EventViewer, querying the log through powershell fails with error after uninstalling sysmon, as the log doesn't exists.
powershell code: ` $last_config_change = (Get-WinEvent -FilterHashtable @{logname="Microsoft-Windows-Sysmon/Operational"; id=16; } -MaxEvents 5 ).Message`
![image](https://github.com/MicrosoftDocs/sysinternals/assets/95627331/6c2f16ec-94ea-42d9-93f9-97adf939b3ef)

powershell result after installing back sysmon:
![image](https://github.com/MicrosoftDocs/sysinternals/assets/95627331/e886fd4b-c046-4ad9-baad-409cb91342f3)

**Comment by foxmsft** [comment]
Install the manifest with `.\Sysmon64.exe -m`. You can then query those events. To remove the manifest, just do another `.\Sysmon64.exe -u`.
