### ISSUE TITLE
junction - errorlevel is 0 on failed delete

### ISSUE THREAD

**Issue by aand18** [MicrosoftDocs/sysinternals#82]
The [junction](https://docs.microsoft.com/it-it/sysinternals/downloads/junction) tool returns errorlevel 0 on failed delete:

**test.bat**
```
@echo off
junction  -nobanner -d c:\this_doesnt_exist 
echo Errorlevel: %errorlevel%
echo ^^ This should be anything but 0
```
outputs

> 
> Error deleting c:\this_doesnt_exist: The system cannot find the file specified.
> 
> Errorlevel: 0 
> ^ This should be anything but 0

**Comment by analyze-v** [comment]
Rightly or wrongly the sysinternals tools don't return error codes in a consistent manner.  In the specific case of Junction it returns -1 if an invalid argument is provided, 1 if the EULA is not accepted and 0 otherwise. Will add an item to the backlog to see if Mark want's to revisit this.
