### ISSUE TITLE
[BUG] Procmon64 4.0.1 - /Altitude switch only checked on first run per session

### ISSUE THREAD

**Issue by heisenbug303** [MicrosoftDocs/sysinternals#822]
Hi,

I think this may be a bug. If using the /Altitude switch this only changes the altitude on the first run (or after a reboot).
Otherwise the Altitude continues as per the previous run. However if the altitude is changed in the registry, this is honoured on the next run which suggests that changing altitude should happen on each run.

The altitude changes can be seen via "fltmc instances"

Repro steps:
1) Launch procmon64 /altitude 321234
2) Observe correct altitude via "fltmc instances" and also in registry
3) Exit. Relaunch with a different altitude e.g. procmon64 /altitude 324444
4) Observe previous altitude via "fltmc instances" and also in registry
5) Exit and reboot endpoint
6) Launch procmon64 /altitude 324444
7) Observe correct altitude via "fltmc instances" and also in registry

I've only tested with Procmon64.exe v4.0.1.

Cheers,
Mike

**Comment by foxmsft** [comment]
Great report, will investigate and plan the work for a future release!
