### ISSUE TITLE
Process Explorer does not analyze windows service data correctly when two services share the same path

### ISSUE THREAD

**Issue by Mertsch** [MicrosoftDocs/sysinternals#93]
1. Screenshot, Startup path is correct, not detected as service
2. Screenshot, Startup is incorrect, detected as service

![image](https://user-images.githubusercontent.com/9402861/41400169-a21a7256-6fbc-11e8-8c62-f9e53cfae8cf.png)
![image](https://user-images.githubusercontent.com/9402861/41400171-a4eb09aa-6fbc-11e8-8d36-d32a263ea5ee.png)

![image](https://user-images.githubusercontent.com/9402861/41400252-ed6a8796-6fbc-11e8-9885-35a7cdcb2a52.png)

**Comment by lukekim** [comment]
Thanks for reporting this, we are investigating.

**Comment by analyze-v** [comment]
Added to ProcessExplorer backlog
