### ISSUE TITLE
Portmon compatibility

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/sysinternals#95]
The issue was created by @PeterMortensen from https://github.com/MicrosoftDocs/feedback/issues/287#issue-312010133

https://docs.microsoft.com/en-us/sysinternals/downloads/portmon fails to mention on which newer versions of Windows it works, including the bitness of the operating system (e.g. not working on Windows 7 64-bit and Windows 10 64-bit, but working on Windows 7 32-bit, etc. - I am not sure which of these are correct).
It should explicitly list where it works and where it doesn't. A table would be fine.
It seems like the information has not been updated since 2012, and as a result a lot of users end up beeing very frustrated.
E.g. ref.: https://superuser.com/questions/927948/portmon-portmsys-sys-not-found/927969#927969

**Comment by lukekim** [comment]
Thanks for reporting this, we will add it to our backlog.
